#!/usr/bin/env python3
"""Self-extracting installer + verifier for the 3-layer injection pipeline.

Usage, in the directory you want the files written to (e.g. /kaggle/working):

    python3 verify.py

Verifies each embedded payload (pipeline.py, train_probe.py, benchmark.py,
tests/smoke_offline.py) against a pinned SHA-256 BEFORE writing anything,
then scans the destination: files that already exist and DIFFER from the
bundle are refused by default (local edits are preserved; re-run with
--force to overwrite them explicitly). Identical files are a no-op. Only
if every payload matches AND there are no unresolved conflicts does it
extract, re-hash the written files from disk, and run the offline test
suite — so neither a bad transfer nor a silent overwrite can go unnoticed.

Exit codes: 0 ok · 2 corrupt bundle · 3 post-write mismatch · 4 local
conflict (nothing written) · 64 bad CLI usage.

Stdlib only: no pip installs, no network, Python 3.8+.

    python3 verify.py            # refuse to overwrite differing local files
    python3 verify.py --force    # explicitly overwrite them
"""
import base64
import gzip
import hashlib
import os
import subprocess
import sys

# gzip + base85 payloads, keyed by destination path
FILES = {
    "pipeline.py": (
        "ABzY8<;$aL0{^|e>sH&yx+waer>N;3Igz?;VH<LD+S!W`(#@JAuz<|VrWr=I%b>=VJS7`Kr*p=6i2V-"
        "x_j!f=DCbGecd05>No7N_lG#5x#x9lW^4+hEMq^{Ebr9dlTpZ=uY`zft>F;v1NU~JCkqh<dD4EM?l1kBPiMRXjcM"
        "inv;k(!S@Auw_y*K-(`-ksEaMO+2Q9In|f7Aaq_TL>H9-"
        "oSn)17xmJuz1ci3WoknHR9O!2lOE&y#c^l7)yT3)qT;AMeC+KF#8>SY%?9rIRF|ZQNx`5$95**+S&YG)>Y=5sP9G"
        "PbG|*--!vFfrwKf<9wRHM1PGhFX6XB7Wl4c<8Z!6X2~CNEGC)xwfj+=%3>Oe({1s~(T73=r^_6t-"
        "rW_?q9;u;nRlLw|L_0#U+`X$#*5@eis7X5G>kSjPOp+e%(C$k=9$U-"
        "QWj#EEv|4w@Pcs;`zZwMEyH!foV3uiNQ#9_7fmr-UbZH=lw#*-"
        "KiYVWPx3R5#VDRmVQY6&nDSc6xwy^pYg|<jPm>sS1n<ahk}>QhUWmn&#1}7M``HAxKf2l&P2-"
        "{vn`(7oZ(~D<gN_g<%X|`#U>*2-"
        "GQne_{{VgvUUv33$8sq1MclgCY7OB{tvNwfE76eEy6J9+wf_ahG#SHUTenF%&Thr%YMJ8Vo3Lm(ft$yJ7M&26)D_"
        "~_WIUE>3oddYaa%*l(;Q@%a8k+WSYGCQg(3scz#E1$mHAAL6MSS!2#`(gSrs1AB8E#^h-"
        "a_G!NI$iVk}1q&AYgQH(X`YF&=y}%wgK`ebZ$GY9Hs*WCWo5_UIVybBwbGKleM2VD3r0oG!wbaE*B~THG@o+>@M&"
        "pVVe1a9T2Fyck`{(Y1g@B0dCkXj?)YE*JA9V9auyEV8_uXE#pc{I0dgt|hK+l1vw{8{8w$^V2=+fW<CHi)9{9MJ_"
        "MpM{y+q9q<|oSY08flh*IJO*pdnzCGo#wM0<GlRw#cw};o?!d(E=!ui83!kwohc^^0d;uR7QXDs;Dd{(VjVloBb|"
        "J(7-yCx!M0Xv+<_nmW6%;Lr9ik^@k;cx_iXo{-"
        "}0im}6WfWmROogA}3JP%*r{gKC`by@q2XAOGRRA(Ff^Xq)70n2cG61eF0g{Sj3Rph9Ls}(n5}*LtWO0iGOwN{5x|"
        "5Km8q1qxBnPv2-fzUqMb?0WHgGkUc?+@Sm*h3T=DZM78Q<Wmu4FvUGr)MHWpKi@?>F-G-tlQ{VRuvf^>6SX91Vc0"
        "KEN0d`G!_d&<gZp^CV3r(Og2%mvnQ0EPUWV>k3#E0Np6h3PtLWWYQc=wdF@SS`xSorx}17Jd+gJ6!D4PKZ%oRA$A"
        "WAPk{TtD4FM3zIk}~j^=>VA*w#jE-"
        "&GM+bfykv;Zgw>o6ApXFB4^7Gf5E9KaD@F0M8jzzH{q{0|0`C4jF4&XUaLSq`gBfnli4ZrGfsFB-)4;88X7a-"
        "=`u3ScGrPXL)K{W&Z2r(Eh!0G_#Am>+=6NM6o3Uc_`6fClPE^A)g`L{7&%aB(-"
        "sovSfB>0J|0c{+`UQ`r=6fPOT^0ia=1AQQ{dc-jP*n@{D&#t-"
        "7%vRH^AGP;F$z4!L;cn_{HA6>z@C5r?I+8_9K0OQ>cZ*~Y6h;>fkhGH1l6mXF;zfB4WqhLO~w97Qh<v0?=l?ve7z"
        "_>4qo;dpF>EZG2uLGQFuyb&5xI5TAeE$}SUN?FY;w8fjdXzoj6$}8biJ%RGaASi)Ud|-"
        "qSA3Ht;{q6XOkXg;0;nipE`$Q$p8$qG*<9<V60nOa#Hv_ywxcJ6D5u-eMpi^Jy-"
        "9Ll{BSOc8V8LP>u)qg!?Up7X}*+=@V?0&JdXyDbU6cgB`!odH!y=YreGnD(*n?XhOAQk91wo*0C{+a$oMwPcjILd"
        "PY>QTYrmYxe=Q}@)m?R3BRbD=+$k~#0E(QydJUklla62CEo8BaveqSkuf;W7=hbAO|7>o+J`{dLAR#0peu!5%1%#"
        "dU_0Rk7-"
        "yZU0xSe>>Z#)X(Vubh+7UJwtK*Q4*|2!9u0{+y4Pcz{7@g@Ax!1obB$N^*Z#K30{=)0f+f(b4SPxl9LLcA7<d)h)"
        "_VH(c~uK<yNf)xPPF;a(unaXmAycvFO00hnO?oM{z?!muN6oni6@Bede7scbj$^I|zcTPVX@14LB;EMi`DS$!niF"
        "Vd7k`Ye8($c{B?sp)1!(7JK_{TCW;)%phw5CA^Kf?buKGOzT-"
        "|jy=j^%tly=#rGfQ=z_hkcX8Al|e<{QA~!J6aBbX^CIo3J^@w1>q^4G+b&C0<{E20KzkHms^k>h_L^<xAR8KGvcv"
        "8(NW5dQ<!Nvhl`Q%j5%y;zAUb)Tov||k{AN;nZvt)rvV8VOHdo`5a&o-Dk7L{k2sSVv_PR91P|a&^W}6}u-"
        "bt0{JI<>?JKz;emTl!GdQr5Uw4o)E`UcB!0Y1alGxB~0^~7(7vN@rD_zDY)bMO?QLaZO*KK#7w%RXRoen4s?+)MW"
        "9Sn~5{<ePtpoIXX!05kjWx9#~13KDz_PVv7vMko<8Ih(Dw_n6tPqv>tA3bY#hg(|`Wc|_Bi>+~|z14oY)!o{b&xf"
        "P#^9Cbb<BOzv`$aF>qZcopzZiDnt?h32*^}|OJ?_LWp2YFE`+RHE-"
        "j?lWPo6&O=od|8HkI<li_N3`UzTw`w&xm;pFJOTx8>GWyYpfz?smuBF8n)s`t${S9&b-"
        "xJnv4PJl#SZ*m$#Zx^uF3>N}t@=s|#Xo7JTk_RF>>PdjonY;Qf6FGgFF;j?G53x~5k>~^1YI>RU3t!K}=qw!cT{C"
        "9wZtE)KMG)USSIb_qGygTWRq#SO&c>3h|(-%)C<E_c|)9!YA>&esZ@F`rz6S#%$^JleFd7mv<Gq-"
        "1ZzWpqg&z_DZ&nNJt9B*}>Y<FMCCr@9*^7&{YCv7|`+19h=%b`rio#&gofIhz*owokdESa@`=OBhJw&XUR?DNTUx"
        "U})}?&#@w>xqQRgR6YndA_|JkDs+;I`s`;X$tNKIf$buAq61+gT#^F^+^6WgO5#A56*$Q0!H`nbBI#7mPl~KIj;c"
        "Zv12t2PD?UsO!#HcFc={i0=57xO;D=_P3e7xR*F|8`XhaaP`Fbp1ax5#j9`Tz+6cYAC|Sr^5rpODlL-"
        "!trr9kph*0$Vv|{~tZ^KnmfFa;yHyhTUxRMQ|$KTQ#@&oBA;vJ}H$jy-"
        "289ASo05P9}a!%yy{}MAf%YbkpyI9<b01Xw}B1R1&{KgAoV*xHst<BuxE-WQi5+v#b<D?iNUxiy3gUE_9=Tw=QP`"
        "u|Qw?LJ_osfx!u8*es57h9J(M&F`GS;pU>VT6Elm;})mgyoOm;#PaUX!{Ll8~a&avVpM2jIS~ACqDb-"
        "vDZ$1O`9KDaf_$`<9TQZ77}&Xji-jo|3+>@T$=u)z8xTPPaq4OVa(a6nGQ-xVtM}^~Lk3O&U_PVJ0{NNF$k-"
        "IT=4yR}DcAy_R{3LJNQ`s;C9M6C_(}DK^BTS#0GgcwwGLPk>P_wo04MEdCvJ0@RPJ>FjHY=kYKBMer_YhxQ8SN!m"
        "66gS!~q=b!+21f*FxUb~_pEvfT#WA%FB$2AwKR2$H#2_8|k4$Nd)aUNVI!=9koV5`7%n`X%6eA&Tmx<fjkE%F$b>"
        "=AWL(4dC|@Z5owqpJEoM_rJFi;D|XV0nf8iwm^eU0k3nGMK}D(eNP07Z(=f9K?4SsKIQ`L8B*%7DN;R03mz>TK=4"
        "a{gIHiEv~X+!FHJ8a(a!gax{C`4M=A)2kES<R49E)&MgrcFKq{CE73aGrZO#Dg37K9PFcE;9~V(=JslB`K?tQ?0J"
        "fBi({_lWZlolDx^hiL*1Iw`hmrNHu=fL}D@$7m&H~p!FFQDR=gd}2kpKruxr5ura|i)7(QZ0H^%+D#IDrLV)SXCS"
        "XIex=Th;<l&5xSt0KlmL__63~RHu3lDyv8OqU}W!=1vA-"
        "4Uj8NZD0{)r_USq?IpxGQF0FWB^5keWD6jI0QM`fAEd82NRo*xf+UQ1yy8@w0Eq4Gw)pW!u@ySgf)GxoHggeVbCm"
        "=QXh;+@G-"
        "1S3IBc@Q#><aDU}Bh)0JMml*~~0`2buBY5;`=d`G8(Q2QB!{pqA)FZFhB`N29XNyT+#w(XFFsnHj<j=fU!-"
        "farAzx@Z9%`e;)T)GLrc<IVMICQ5e!Ng9-2G@WTG?=NruEWyj3G(MG2_M*<@Gk|cTe1_HNC`l(-(6GQ!OCQL$k-"
        "CFG0#e^2(7ml!gjI4}{<Mx3kESxt2Sg;8t-415nDWc6_z8$C>Uc+Yr)0RQ*{DEC%m55*yt*7kqil-Ohl@N9<bl>O"
        "39|E@UgCz*!o@rCoV3V7A+*;eAO}sW%f1;>@UG>2q1`iKO`|5snt`Mu*}z`jFK0t?T?mwwVUcX1<J*9jwMmjV`p_"
        "b&g6L#u&OqJ5JyeB7`^ENJ!3L&0Wcdea91v2eq&sC>7NcdJqp)%XsvXHGff0hX?_E(vv{Flg6B(2YFj&Qv+YjKi@"
        "c!4J#=*kIEnGi9A)Y1O86K{^AdhIUZv8$<!d`0M{zGrgfhQN_;Z-}nWjR=47PNB2cTi1E(1<z~tXwN|-"
        "Gby>Hs*`~IDix<GtjosESU<DQ2=#;oX8yQjo(@=!Lz*0f${+;=fEI9Y+M3YACNnM^v|X+KMj<)LEocozd=V2f0&d"
        "1JIqx+AdYu_(J~6UqF|e)IyMCK86*E$#FtunKh<t5T+<xg5(Q9h<)`4&!1F?UAunc=e*lGv^n`=X<^k~tnv8xLE|"
        "ck4KVwNVd<jjIJ@6Oeft&0Zji<Nq9VibH=mYz@N{_PglZ;U-PKM-"
        "$i8gF;q&z)1AnPmzpgEjZgwM?tH61NJ(xB@3`o=2l10Ja<ZRJaB6eC8ZfB5`c`dj*Q?M1JCOFzMk@axZ;^&cAw*I"
        "f9}KmYgO#9*j9xhDP{vL@8X-bzUIyc`ku!~4_Y4=1O4Zw4p-gn!-*_TQhtH)L_fljqf(NT9vIj<s*BC-zfDP6QOd"
        "x@lG@J0u|Eh36PA2!;i(wE^@|7G<QwM?hwvs}@!i*)ku=NSx*}rl1UVUr)(hLGF7*bv+%dL*_|5eJREn!N3Gqa&}"
        "9uT{K>jnt&@Ibw;CEvWOb!McDWc;|x<a2py|(EDI3A&5fKWuQWPamkZnjUQaA0%jwkeQ=n<Pv^S6kQjU9o%-"
        "K}kR9s{!-Msp{n8N~P&$VH}>63&_A`@y91H@rj*oH82zVSz5R_7#tp+8S+5Cb%Gp>8*ZhZs*lG>UP@_C!1B-"
        "9sKVj@1D=PX@E1WRmTu{T=uLhZS|mvhg+s>D;4~1xjISa)^f<e;>otDS+v&c`Gff#8td=0L=JS5OpGhe2f7Uvb9("
        "u%o*o)#ca%ERnhi?44tottp&vxnN5y4=0rub2##nekTQdsdd0qBWEmMK0e@(qxuS>`4ec=iQ4Xr{I2$d=v`7Aj1O"
        "t2|j0$kcsMsT^zXkP2s<*HRooBbiRsa)WP*@W54OXn)f`~GVDMAErl=zXB+U7aPUBJVFNs<?fP$~PxT#o43!P}jK"
        "gV#H|e?=Sn*%$Z<8s{5EydMnE$vha8_7#i~DNQN#&Vex)Bf<SLr-U_?@%Q&oiiWA4bh_ow1cC$Q^fM#c<p7q9EnJ"
        "5o8rQ3%2FZBEKs<BJ2d?EE2>xSM0f0P`#OZFmu%<x=J`tGuTXAo+fkLnR>9(>pIl9ut1<!hM0kj|08h9xv&(lTHx"
        "<tQ=K+oiif(B%C8CBFpdbEG`)i+@OS9kfGmv7qxF;(z_Zs1h~hOzJkaZCw)B*{opSO<LdZs#95u!J5g&oL+z4{V{"
        "RBl8;y!V8<EWMh1c{US1=ew-"
        "6iOj1K}O9R4AYR(8GrRfqM;@G?v<Hx_2Nq!CAEny3Ar{=647nW=@mkTmrwSYOIPK{U>qtT(5C)c<PGz9=H(KwGLK"
        "OWgah%qxExV8X~a7mF+w@c^(H=N5Ex)W_&-emoTkl1f-LiCHuY0#ix{_qXLnb0~l1>g)ALdc-bAK8*}R!(tVnZw{"
        "Dn@)5<jx)%?Oc>|<U7wHfK$~Kkhz~*eeQ4Q0V3`J8S6f(=aid?3-6-"
        "u+Z<M*uI9__nM2S(Cg)*N~kfx@p2M6ySg9L>nRoNTs>%qm;7XnoL!B#+L;T@8&FWJgOHxjhfS7dFXuUehZJ<H0zD"
        "|ce}DNr0DOs+_RB<k#(j_4EKdy~YhCI?a!pWVrr2M~}1p=M0qAf#ZmRcWB23Cci=0j~_S)h>Oi+Co{%mkWoS?rD7"
        "w_552z0ggdX;YfthKugF!sifw|zwR8rJJ>rpc`W2&<XEK0zX+J#7oXsb!A)p9kO({Ev(&4LFoHl9LHOBX0SnOW>1"
        "h~3kKn&aYUYI-SKs(TQ$BB4VEsD5Fi_k92?sq8NiMHYWgTmJtGC6Xjv#rcP|>Cwkx_Ln=>;Nf12i`$O%B$s3+ifY"
        "6pzONo`oKJhB$2=JU1s~A+@$Hs<**0V62UA$Dt*LV6?{oFfJhRqvD}<LEC|V0}L`Z(b>#NbS&;d$4NQ2to`F~QB{"
        "w5CANc?QDUW;4<2>mu%e3FCveFIp&#jI@TwWGBcK*z*~gf&rddv3e+XRxM7?W$Y}j{NfWByiX{6%UA>9dJ20Qbcj"
        "1(-0Q<(o{WH3Z|^-"
        "Ba{1c$kp=G;pG%5{vU6Z937F>LPs8mKu`!#<jI(Wy`WZ&u96>JIx0H>%Dh;(d!ES0><)Ry;sD&k7o8j@qxV+v+Oj"
        "gX_L4QiguB|3ODVIR|2+nO_8aa{Wg|*l4QjF4#}Yzl1g8|EC5HYxLCU28H1D@T7HQTLFLahq?d>Y71)aOnT5fkYh"
        "-Qa!ZyZ2-"
        "YIynBAoqt3Q@xH}gyviy<8TWlHwnDMwJCKuEe4+VXVZ8v?1k760ddZ|{UrZKB3?3hLIttp5w>czu(NArWCbh8nf}"
        "Y>_UDdEzB|oFs5ei-F8@OPARDIFj_)SSwsV-"
        "}qybghX7dOhE?4oQ9w(_f>o%p!LhkcvSKY!I6WcTE=tWl^D&RIm)F`Ck?Uze@H;)mWZms8UB6_#Pn=L3!?=w0+;G"
        "1Fqo0}OP}UCUlYKO4!-e6%f-jDhczcPNxtx+axHbI8%8#H-"
        "{qnUU<q4q8EqI}6jD3*QX+Whowh1=MQB7$$9yLx|00&*pMhe%YQIQ=1YrOIl@{QAaG7cLuec{(AMCZ;Y{!8uv*X&"
        "Fi~j%=xWWC&btj}ul0oBboJ<)@DQC-"
        "&m`8>3BJvSQS9C|2q9%*F?(P_4(vLwhPG)isQw4(BdL|8RsX{!W1Ot>&Sd+voD%K`@C{^*cJ~u*JR60_C%x(^hv|"
        "=4A#CY>8y#cyH7Ek2@T%%}JH*?lLKVvdk(VA>Q!21wU)AMqi`*@Y((JYI=JCh=1=YDSBvO%~vqZ(6~2Y}I|F&|(6"
        "S|MJg^90hh>RUlCKO5<7S5V#>c5XAOZ>up7QB?*zr8Fw3(AfQn#u{^sBM`DsR&cru=etk_pB+uEtbmqz<@7c~1LK"
        "%Y-"
        "U{Y`C*5JzQW~S2jdpZgQm=gKNAcs2S}lgNnazLvQMB}%kadlaMo_X#EdB*^F4$X4mcr6TsHg*FpEcPu$ri_p3rE$"
        "yxX|X&VuqN(5lAdgTwH88B%J&?*%Y2CILMloPtn`|cZa2($k~U^^^18E7}J6J1iyoCf!@#dQ`g4&a>Gs2n<VIyP%"
        "|oz7lj?N>S7G36m%p0ZtSN?(G+$9*c7e0=;kv|j3|hlZ%PVS)ff~j^7U9|ZA`u_tZ9Ooj0<!=^u+dytv2tTqKvlN"
        "&&-zKPd3D<Ts2I3N`aRSv)M3Q5w$lq;%upFz(YV(0)*8j21*g9PU7i+U)z6+T4~dk8|j-"
        "8!BrX}+fO>}X3bL55?z-"
        "PvwQ*={&QbF?F~CR!!=n}zS5$DF)MXbPg5^tb5m?v#tDWbwLUY*0KT<0(Eam;u}*Q^5^PAXx2fi`_~j1(4jK@9oI"
        "1-8h2|P{RZR_30A~qi79dh^dT25Q{IMn@CmO(wO0orht?|#c=5v;sNlnnnQ`IBp-Gt&*)z(#sOo3GlXskLTYsYX("
        "d|a-"
        "CV9tp@ob_tfw3g_cS7Vpd;8y1xg|G6pb+L#?YKf&B>8_$87Ssh|U@#?_KyMsr_`##Gz8MarEr1eYx|zB)`1vPV-A"
        "mD^&&e`^$3<k>4EvbR!>QzWQ5X{#dCc0CGi%nqaGtQh)L1Of&g;>3e0J`c@&k?pSP}rxbdUhRb)O}@1oqB1eh%xo"
        "PUcl|fJ$RsJ>wTxN(OPH0jflb7lNiXz~Jt?sxwkK^GZHReny8!9;V7v@)!d_v_B046jWd^?H+^qX)23P9^-"
        "A1wJA>TbkrtA04km{l$_j+wg`ZYCCCxO<Z_uU3qUNDA7sMjQc~Acau=l-Fa^#5!gBH;3+-"
        "H^q;b7c{5>fwR`JV+o#Qv+?auzehvU5_Nv5$0&?d!_wMm~6iE$w%?X78{_#V=n#>zvNjxn57{B7@e|Ly+X8^Kzl("
        "Spl^mLFsCyDvbt;En1`QWXrVE*oZ68^Z5sWEp&#rIyE&o{z+iHg}ol`2@$AWE=YM4xJYOCT1S2HXuQxrR_ER+>B2"
        "g(ZIl#mSh8h11C%`DRlaGpdM@zm8TR^GZ*<$Y9m3iRfDU1O0S?CSRUte#aqeAzG|W~_3^x_xv1}b3d`TnCcx@SgB"
        "2lj(3GZ*u>`gb!c_?hviuIGj<Es$COx)1P%Y4xb}@zx>(tS&5V)p{P}@;0F@fQ(PvH?k<zZ#IXbP4sLf5)L;FkK2"
        "KpXtfasuPjf*Yl&x5|b10gNZ(W2kc<9W;b=i07m;Y@FBT;-eq~HO-"
        "0_1vAsvo_VXc<yCek)jM>_&L>>ZWBUB~{4e=u50Bzm0tbiDw!{`T`a1j^x?1V`tfW^heiNShEd}B5LTd7bx(~82b"
        "=KU9!HxSbM*#_*X!UIMxz>++<wgD={-!e}t5lD5j0#yQ$(m=X(o6_kh%(qk!1O6phDBr-B_*aH3S|w9R>4>&YGZK"
        "+hBWJ(ya0DU{7f3kwQO;uPu9FP+>{K^BjuFaP{Cfr)5J~nIBDNAR#O|6RIqlXjnofpXqvC`Q+I8RK#fLQJlB2D1v"
        "ZqyNpiIY<<uwh3}{jY*p&fP+cQvv(DI2ZgmAnST?|)3I8$L)wR9VPkxwi^>!l-"
        "@;KV2<HaU18bo@N@RnLBxE8ww2MFlMMFcmy@cJ7i(LtA}@kc#Z@GfLtPjN8K!<jlP4v_cP-"
        "97{Y0u3to23fURx?^!&hA_LmtrKB-O#_`NZQcn+n4`mC~pg=CdLtQRf*`!4}nu_e8qz-"
        "ayQ*exDE(a)B?ixzAx*=`UwUd-oHO(>%viHoBav=RQxt16XS4Z#Cg?SYv1+O~5b0x-"
        "zKLzj{>c4c@@GoYG`0c|rWSTUR^d_Dr%2ehE!k_SuzmUzbIu8Mu)&ZF0(2CrV4>Rv>tT53^mO?CxthSJ5sYWrf&{"
        "`4(o9@V5Tb<R0d9(7yr}E*)`0(TN&%oYf#m<UG;+6_mCEDG?TPZEHYGF-vzUXG)h#4%P6NFay%?~tG&&9QQaujPR"
        "Wyb|720{k?SzP>UDf1X(^6c4SR5Q|KhB16t00PM>3WXXK09?oi@V3?Nh7Q-"
        "QBD3+0+XqGb*lQ~N8f*6s9GJe&+GUF1)8m)oar8T|MRyG#U#!wz73)Jn7%&~gt#LRNC(i;ZC=yvxZ9;LcU9}n-"
        "+pH*<F3CP|YlU$PFOV%<6M0&=L|0SHWqeJj)zsl*ix~4^%8l$=QDtN~aRbU$1(HSLmok8?)Od8n8rdq1NMgm5p{1"
        "1)b2(Rio=ua{9kOv4jX`9k&_b_EizVn@?}(xD#46qteVpP|zYDkkRL|HGgDh7e+PSntw^&BP(;$-"
        "ursT9J)R|1b$lLz4%(z4n6}c#*P|+I7q_m87)K)B6jN&Od?NC9IG1<9jTFl}0>U+lO!HlV5aaUpPZgeKx$r_HzV{"
        "E=_Gy1xDg&Ye$3)&0=3;HHD$&oHbVcimg>(b<G=KI|t)i+^P7c4jDpSx*KgZluC0s?zR|B4^AA=FDFLQ9xHQxuw8"
        "nOWdd<`ov#NCyl^eTtkbma|}vkz?)X37y*9oSJ&hqJ)eH23&jM3Q%%}rW#FerZJV~iWgXj3@9tYTg4T@bO%RzOk$"
        "T-"
        "2C9F*?ipH>>GOx>Fr7NPOwR3{@$s77x%e#Bx|LyBKhya$0SxQ*aTR^&(XC7s!M<piFr@}3#N&Ob6%r}s0z;NfqL2"
        "@rEYSB#QGi))&;H^`=*(~B1}j>ntEiMQFO=TOyHX(vYKyL!vq3La1363)qds^om7#p@j=&9L&vI0`f_YPHhaLz#u"
        "S~*_hR=PO8?k(tZ+-w2oR^JrsYTqFMNk+A4Ln~7JpS1U7-"
        "3H9uX5byhxu8RUHZ|Oi9UXSqv$`1wkHbJ1`5^sAhLNKullykT`)kn0}=bJb;4-"
        "FP(6V{N)jk}F3)J7Xye;gsCsKvx*P)&%9Hs5<P}y>P;}!jhwOyh***QRbHH^Ql_{6SrRK&DM2Ss;>fEF%6?Loa>o"
        "EGp8zDVbFLm&*WeltOgS>MbQ(en3!(>8x80lbTwjUXKc((`tRH0g=_bYKn%SVqv36qbT;_>z{S+stp83&kW`wG8&"
        "4qrY-Qt_DVBfXzFiuToGwxn~GRF(lHPq74A;jC!D0eKCwz+~t<iF20AWq~yi&~rwXdu^WKg~Npq8f~|R3CF2ZOx<"
        "*P=jI~*Yc#=d=t}^t#Uc;%zZ_zR1`m39lVY0yY#Y9%sb6&tB28I~yjDQnz>{j&9uc_+sGN{Wx}xwow}_BsEylT5n"
        "2Kq7{5`5pS;H*7OP<Xgs&_#PYfwB;k`C}*8)0oXlLlS*CmQ^Cm=0;+puGRbq}V=Iw#vt!8~*8^`=@Wv_in}}gOGY"
        "7zlg!9{whw*94OozsGM?@0IqHr*UZ=G#SP9sw-"
        "6ovSyH(WH5&q%LWZ~SdRT7(%GVH!7;@=1F7&3nBK#&wAapX^UzW8mH+1xY!nS#w1M|U%3mS=j9-"
        "a@Y*Xa~5Dq2jHL8Ks)98oTs>iyv<O{YmxODPDs#FBC#$f(LCllv0pUA#e~tT{S=(gOwkYfvi(0}>fPajwL{BlQl>"
        "VeltZD3Cx~vJQ50>{izA7;P3{#yDSlWDd0mK*-"
        "`61UkXdwR89**owt+SZu1?6m17BC#}J;0?NjBOOWi+vYZmu7+@Uds**K1oUPK+Sas%m<Vf-gPH+K7_+mFpa$mbti"
        "(2(;1<1OHHe(Bw7R9wH4BNpRgqAK1f}#zTgw}i1kK46@Mijqq`G-"
        "q8z9*A(mXKpJz@#;i4JXTj%KUC}FbpE&9V7MaRfbtsJOhIs1~j5+u+XmBA;1KWqn)Ny%X*F#fplrvah_ml_C<y@B"
        "N(m9gyk0JFjHQ>%yX=-"
        "eOJx9T#=QMVrDjQMmgZjpn(3Nl)k1)7OLh0Vs7ENWj8TjQsR?qD|sWw%Q=?erh>7$&VV|6^oPDQVY&QWpK?bE^va"
        "CoN5{NvmWmlC$`yqULSAJUvTKgYDRHPRDwFg@cwR-ba;~QJ8J(|Rn<v_|VxRR1Vm%Nmof9j<P(r*)E5-"
        "0mOH96+aD;?Ex7(WEVzitp4nsJ`YE9-"
        "T);X%I(SNhf`>MH|{G64`$?g`uJG@)kA8r(G=|+x7GNvpfs<vIeKcUopg@ie=JH(%qoG$@JaOY#VI2FkVD*HrI9b"
        "7f3N)~mu(?9EUo1*iyiKi~Q+viRghpIu=Q}n~G-"
        "p|o}G)YU#e`FXPCliv%Yk6~w<<{?1sCSAMyE{PH5t15BG;WH>kE|v4qL8gH61(OUC?=C~xJs<S^5vXEDrfT~XBkz"
        "HQQ5KrVicC5ikI;m6t4+|N1#bWS>k9fn7c_I+_X(Ae!@xLq^tp<a1HPz{O{&+@=Q(Z4`cuG(<DufDmjA+sW7*RKe"
        "<0^q~dHE`uMPX(8^or0vIz~N6sW!Ajo=JKLj+mPn9YtN2#)Mv|rM$E0dZzfj44Fm+=V=tOR76{ts-cvAh;X$E~s_"
        "gr{SKJJDpG4@~@JJF*-zR-z<kS`VhvSzyziZ=N@)3boxC5=^H)D48y2o45={CAOpFh!tccXHwWDt}3~3Ea{m`-"
        "B|H%JeTqq2j=w3jF)<p*?(s-"
        "<@HqZY|PoS=b}#iJ?S@JlJQqT*>H8>{}*HcRwiw71ajX&$(0Fu716zttmiWWX~$L>k~oJ`V#N0*Hm@9A4{pv1AK7"
        "r8B`-"
        "q3A;OJ3xx89f22Iur`}Y<Z`<k3<RgSFkfUg9YWgZ5V%B~lqEygxn)oKP_idWUjj^$MKa{R%HB%JaUo}0EN^{9M(`"
        "u{yol-"
        "7iPBb{tF?is!W%o=A)EI&w3u2@vKu{PoA)aXgHLyFqb)};4uw>dk<=<k?<6*W{b;)>(EW?T2AF4?C@emhB`6sizu"
        "W|!j=6G|gQZBNH{+y3nmMJoxnx=q8EVR*e%p}IHXZfpZ!x!iM+9#dH##{2S8?XEKhGI?TGOt$a?3lnKnx%U~6%?2"
        "YZ^(SWlAb?OFsPIv<YL4u;p={+bM_9u@a03)9Q}iXd3-"
        "HA#B!c40#ivZG0A+|)rXrfrn#p5u?s=@eKUJzNqS$<ETU2>AN5ZyE-"
        ";yL&GPqJyu?}2ThNeq^Wvg<k1!5LM(;q8xiUUHl*#0W}b~$h5oCoDv2byfJunCrPkYVt?i3Zt_s{4*haqkD}ena="
        "eSp$<SzolRtEG}l9CYx=jzF(nwVg(pQAtrG_3CG-U2-"
        "Ib9c=#F}omPFr(#5J&W94Hl!AfPZr_0%Z?`=?(vxhM*`)tbby~e4fCR85ffMSuR;%D=!(1}2XNqS!#i+EI83oxDU"
        "6HM}%td^kQaNHIy=~IOkeeQ`fPyj#ah14TSoXfI~Mt|I>rZ1}V9GD6v)&U}arof1SoDC%j14R%<w-"
        "N<`s8Y&gwU5nWBY-DkDrYPHG)qE<+n-7z*5BaonyJ7?q>S`|!!-"
        "IeCtOV`(~~z{oy<d_wQ<&l`v%ayk|>v+5AT_MzwF8X;OemD3vqc$NFp&>A>)8e2i^#vbRMCqmB*G*80M;pgYKPC#"
        "+%2`JOCBG$l!(=^F`x36i-"
        "khXTM_fvElk(_@F{|*vMIfAv75mjq|9uis$mIb6ydk`I%S!s$$&x!knqDD(mU=K6^CQS%@f*I2?j<oPg2#!iZ<_9"
        "cS2ZJn@2Uw-"
        "^_s1Az*Zrq&*p#WVR%KVA344P0vAg;clH2mDYk?2%DD(h?VfAAf{#O%;%;=_tEeRM8QXHK`V^PJVRz5PS?Q3=HuS"
        "&|?nsMb2d20K9#q{p*v>iF#UZ_*{`3l_ylkj5R#-"
        "eDW{ovwN2c@}rfpdu$sV%vJhdCD?|GS7ONom&>@@zQQMKOF1(SpP#kQJ#zmK;tYTseWJ5^X5l?-"
        "+p9(Lq$i6U;1O-sb`wmAy-riC-bcO^Iu<208K1eYEQod*s*K;U2oO6kXOvBWXcK6mKmxQ)C2xDmg4{2Kps(wyh&*"
        "b@EH19GkOEQ-"
        "p!t}HfFc!q+rWcGyuk+<S0a$*0FdM#GH7)|ZgmmVi_W{II&J&*C_7m3fHV0O@xu2;7!(o`8U`U|l-"
        "8q%mC3meuyJNha$Z-k@RVm5KcJVRONXqU6ZT6nZ^d;;OKFGLr?y-eMW_d}B<)kB{*C%14DUJ~jK9-"
        "|6@j(^|ECUnfg9cSuC%WAY!mrQT>wz~8ce}!RqG_nlS@oVulYUZku^<VFRm%#k4e#QTX_zeaavw7i+kER1S^>+RX"
        "WGy3QG;3?B%)4lWd%fNMmhrOAacjk4`n}I>c>+Dk%=irBF{?<u$p*V`!BXlBs5JYnfCe1d0T$WfldP+1d%kBhh{0"
        ">2y)E3+(Zv81QYo-myZ(=A$t%Et-#mD0!uIL&NHN>h+7I4sn6npYIl@)33NaQ(D>s3}tfxx4v}Mw&{Z--toVu^xi"
        "DK2IhMc0H?t67=?0gqRKqi<(6Hu@@uSf4vOjS-"
        "?*a2Lgp{^c=L^FbR93P7NC=OmQc~5gxo;Rk&v!eT;nySx~7q7My0xDo>22+%#ix)TiaHzv@E@3UvxuIdDd*VuRnm"
        "CbhVsJrlt^DoQ|^@v(Nr^H(XISwKA`j7*b3A`LZqkg1d3|xiY1wzRB|Gdw2Sfm|9z^ddRU<j;35q!<!Cs3VfDiw4"
        "NsJ>X<-"
        "d?nK)HgV`|GmX|HCH^e1%Z(em04?749MDs3kqq4qzx*U6jxW+m5w~c$aGOk3>64aX#9ZzcgUwr>7Ze4BbzRlQMFc"
        "?l2%2kf~Dz$4?>hr0eD1xEHRpS<O%9eMUl^o~+47A+nCP`p@<z?jzvaB-"
        "}VZtKNR%b8V??XKGNW&Z6pqhq5+TJD$;5&|&(DE_EHMxOe)Z~kf&}r?3<%5{aX2A4Jv^}=qK#x8K25>cEu4S@N>G"
        "_pXLbSOSbqEAf%Vl_&nqv4soF_5%or5Ky$&Bm#Q=Vt+paljmwZ=;<j7m$U7*BT1a|MIpopHve8EQ-csPb9sHW`B;"
        "GP;U$r%=XKHp?!jck`<vjKm4ide!k_rqgpK0Djci{F*n&Ii-"
        "~PpH3(##hP#D!>)?k!4$nn9AWg+#RXsN#RUlXXdtJ;(AFNC+$4HTzWb@IDqxjneKsK%Pa>{!r>nXEHjKwyXd4%5T"
        "7$Udk5u|2jVQgz8YTeN_&PB7szvopq&Pm@#l|`}7-"
        "?rMh&)*wUPT42lhHN4yPOn*ak(i2$!ef7NbWx}nIt1@I+Bd8toh20xzuMZml)_kRV%DHlY-1-"
        "02~uxZDqqvLN!tS>MdNPm6AkCnCJQiC_0t}u`EzOAp)k#SKv}wpsvG)|Dawo2Zw*(J2?%lm2n`KeY}8dc7dR~0!^"
        "hC7bT4W)S|=HjfHc`@h^P+Njkzl5R}k&blkM-{pg6%i;L_U%i;hy#j{NHXW_Y96MPmcq+wFvNEVUUM`40rX60Q-"
        "({PW=a-"
        "m)%sHP$)747Inn{x%TOSoHQ{c%o7Wva0;8#x!LS%qjYSR$X1Tm=Mnq27W<!^2Z7#%bwax_B4J&eWM$9c+UvN3_#6"
        "Zj{?A59|9xa2qbmtyTIkkMnG<ZW76z3yuD;7Kg2Iv?SNR)I6;o{;@*plen)+kMy$Wt6k4^kV_l`Qd%||#LE%4^x!"
        "`U34MmYhwxt_VS}4^ioU%uH6Jg(qL=umn`1~~Hp1<pi&G18PK=7v*32+SCoq?-"
        "93*qdgo+@rtW(V8bXrZ8cA`_t3D<<Muu@%qW$DvcIs~+wxF9V@7mBTL+CfZZB&~7$J%tzYM|(S^7jZ??I;92Tk-"
        "3Z&DIpp~br&Y4u|*W2J=3QX{zID_*Qit8CG41SNdEHVqaXvY%A@`Vn}e&KVH2I?-"
        "ms;4{=;Na^4JL2`~X&#7MP?T{KL+rq;ke}BnfKfZ;ZU|Z@1g+CZofE-6;LWFrH#s1M1Bc`MfE1`)#`!s$)Vy-OyI"
        "!dPa@I!n{P8s8mpjv*XQjiIAFVNefI;jz&_pDFBioTBb25<1UP_rkn~xh3mUBjeL!y4H5}irIfT+HVnWgOV!1^#z"
        "~P>u%{EV7eNWH(ITUAb75#fDFLz{Qr&KlHJEmlul1|0{@OG%T8kguz-"
        "`_*MMsTJUY|hSPv5@{8>(VBCrq2IO@j9GEtA@QNA~pXwnvS_A%T4cbW&JgL4SucSzF1ni6?l5SK^)<kZh_f<&xHb"
        ">P`Oxwuv<`Zu)pMs^40_p(uUhLHa7M&pIV<X}h|kk$BrKuBt^PAjm-jGAfV*%;o!Ov&A27k{Ad?&4;MB79n#Fu%`"
        "+BQ7p#zSzWTHvUKAfz^p$Z#2E-"
        "F^az%n?74Opqa2`v2nBIRG(T@NH&#dR)K=oR?BD0;qE)`PmME}UG}TRORdkXSYxfskYG6XX7UGqvVW}1@^Hr6K6;"
        "qL}p&;c9Sj)Kxh~ZGmtBmG%Ttbbe#F!fF(nev$Vbr)M4$5n#Vf3g;7(S@4!SBPZG^}{`8)|mW-))3vy=Jv$q_-By"
        "$I*kUk(j8fLra`juVr%|RkH{l72!(~n30o{%-pzdH;qMRsaBTWh5R4Z7_P~=zSjqP3L@}C-"
        "fE#jpmTy5YX8x=DU@C1(U^Umxtu03HFNzNfUd_2>(vj%Ep`MW=d9iZf@!G@`YKi$-"
        "qx%!mes{7QN~La0l`n`56p%!8yk-"
        "1H%L^8xyS(%n57CRj<EDws;bL)WO4VP0h9ytCQg|TL1?7#Adn7#94dhoNg_6}qD=Ruoh5JAl&(uHrjz0&pnZ=kB-"
        ";uRJ5o@YGF5PeM`{6bhiJKy!PAwhhJj7>SBkYG`}iEJ*HUHI6#`f@k3J@ttOS;zgp|;VmqpPXjZ!ej!uqH;O|=rW"
        "3KZNmo!44?`kICKTU0~?Gbf&ur5o7Q7M0kRT~{1NRKH)adhLlJw&L(v^(a?*hOX#J0X9-"
        "Q2l1k+u$Zk@9{LL02bP4f>@n#aq~xo@wFSb;&;3VHcR~~k>&Dq6OR4!jv@OrfzS(t5){~|1qJ7_4P-"
        "Do4!mWe0Hhnh2OrxSaBe=kn6+hdA0CU0rzhbiCK$wPJ_p$7nhn7Hwf3Jow2gY!=_3lGIKi~H;3}xWBif<$t-"
        "+&?E?q8Z5Ah_5S@&QSDD&tt8BZrF~9==tkJ`7^LkwvsZD%C&_J36C%A)cJ;C@=#6zNqR41jTUxpq0*oaN8@X0oR|"
        "9*kE>K!}p^{wYq=G;uEXty@VJDCO9~(Y|aAl>OO3f#E+uW29RymL0SK@x?}|vtNjjb1XSbmTI@%ew_+04b!}uF6y"
        "gM_B-E|e3Q0w^yU9wV6Nh5;q14R;Owh3%ZR{;-;qe#;cBmmRjMY&rwJdOhnz^`dl6B9T9BjMfqdwPKobif-UA3Fq"
        "^Xpc!B7nIvCmpYzCbSk^07X!PCLpKIV@wCtA&)LW<x-"
        "T`mRlLc+3r$^pSWeQ9okg3s4U$<+ylW3!IA;_xL98TWkun}mC@%YT~^}H3k71E8YY@<5+fx)ndr6~oe5WNZ-"
        "h1pgx97{D9<S_y_!sj?=IsDBi(lBTHX~V!Gj@dQ!QMMIZKYL`RMg?;#Gi@V4Xk-i_eP{y%yNQ`g=A6Vr0JMKcn$-"
        "Hg{>|r@ACSH`(Y}lCnoLXXBk7#eaE*P1%!Z1?8<8M8%oV9A!r|dIqZ_HtXX*Jp;>#Wj%IP-ifQM=+SGKP@|;gdbB"
        "0#_`*>&2sC=@gHCC99of}WYsiW3sA|-"
        "!I!%q*hbzxfqXE`~^3aj;_ce6si<1g{4b>bJ0v)ZTI70!V>MRb~Q(nWBp1;&^SsLW4j>g5=hul)cT@p|Q3mRPW#+"
        "|p)UriI>d)wWy$b+PNjAWX$QT?z*+mY_Ar0oxh12_g<66;RJn&6`{sl2qh0u0wJ*<{LS(|1ZkDe7$!%5)ChF~O;>"
        "tg`LL8P}R2UjbF&K!cH$Z&IiL*+M6MBSdi<NWsVk-"
        "@rQ@9+AsSU@BikOi?dU1eMOSa?T8=ok+aK6;Xbi*u|Y&0Z^10H_&->V=hK-Q7k9M-"
        "W^U&5u9)S(ywC9*XGPPmzAZHX@Vuo0b-"
        "L0HZD}J#Y^(WdOOSdOa7Ug>7wV89Pi7NTvpY@8yFaQ=R4*cLO0HY>b5X~Sy#R~a{LF;jZ`ueMZB-L3X{yE?n3b-"
        "?>*=gCZ7qoHs6^&VIw@J=E=@i_q$u_FZS!UwU?`UCsfiTEEBP+^G)z;+gVc4J}cw@Vii&;dG*)#9e5DzVWBt+{*+"
        "gARTF|T`O96q4U&q)7p6mjy_?U`%DI1a9I~DoAV{-"
        "R{wsBBnPRaXtAtJAwUS#9yA_Fd@kgP1*aFX^N)s;R60IL7LBb*;rL5s5>Nvw~kVAq}<>}=lil46rI;<auxq<flA;"
        "L(RF=%G{cLE7<CM!4Ule0nqgjM&8nJqrL<;>;oYYntmZgjU84KOr0r$$>T=QxRC9;bfbv2=)gKxaD=|7Ei`f*Hj{"
        "u~MWWrdZyCNhdMy^zvmHxMR(x@&cwTbLkR_NJsRM7fR+B$_a`E9PUH{*(CWGRe_ZgY!#%|#ati2;v=h#&`Q!$6W="
        "R-"
        ")e=m~cL2cJv;DgPbrty3HeuixJ`;=8%uuVxEEBAnkFuyeliGVHhHSy@s=3BV!4*p=s(+l^NNmQaJgPn+i{NnO$`s"
        "JEk8zzJv2NYwBcWH;;7d#Ap%-"
        "%WGhZXQ`=N<vtP)siK4c9DZGfY1{@oDg9*+hq`t}~;=!ZC~uBw^S+2F&7q#vlbn;2Kea3ISjm-"
        "j=?`iuHXXTH)%nZfJx?p4p?5y@?_E-$;nvR;-"
        "3erdJ^M3@a@4((nsLA{`X1s9a_YQdn*IG#jGRWSxHP}jAs?M<r_a!R6sr=;L0X>JGt#NTEc*g_J!x`|(xLo~k4D3"
        "rS*!(k_jvJ~2!Iu3wpXU$Xosts>$c{L|AuF7nz;t!5~Wh@m|q>%zs>yhB=tQ`Mci-"
        "(5;nnhJfN^RBlfZsNJK}(exEfS=^`%appee>~RC67Wbpw{-"
        "uUF%t|(>?zjMNysM!M2sf);A$w&!_4p&1BSoqoQM~7O1|t%$wCb>$J|NkvLMRqEz3T%o#mORc*1jN5)}0rBo&FdJ"
        "&*1JL1ErdT=YUh0I4+SlI&OF{+4A*1A)8piQVAVAEr(u;%`%4Gy|A<@bk~6*AI9??tmO^`~olAel!G^cpVg-"
        "H`NiTvOlp$8|UUEE0RAw}M>_aEMs>BR~$q^b#9AVI@aORAoPC=c)L)^~#!QsJ}+*lj^X91@JM4<q~TyE^HTx#se<"
        "jT)BK*kVaj-"
        "$DyTuam}GVLZm!=_sQb=jrZA8t4!H_UbWZ@j90B0T7bx7Eb>KPd?o*`10&y>$MCgARIeQ^aQr&0GByX;+oP4<ach"
        "%JcZ<#S+TU~Fsb<Y4ilT^903d8-R<=U3Qeskvv0JloODXD;O0HZ=!f186)HsC-lVU#!js~UV7kB;eiW2Zj_ezsOo"
        "~kLTgM>o=lCjlR<1R20g<nf!;`(uXGP7bkLIuyUP%YlPM8;}#2FHbEf;#6)^qedyu>sH;ZNaPQgA;c)K2u({^A+L"
        "q>eQ5%ZH*PuQ=rgT|J;!)25L+-"
        "HCk5{O06)DrmDseZrl^uRNmpe`4{RHmUpd5>678ZELonjaO$+y%~TH$Cdt|FF$PMF6_(D*VoI8^JVFG?IkcqQ0mY"
        "S61B;DU$5Yf+J2Yz%BrDyF|E?gBhj&7At9b_|a&Z%58Jl+Bz)*`@R<MrQvlHiG%7M^zcx~^V#&YWRI87RxF3PmjK"
        "ynoZ;1oCn0n0EiUx9}R7Z(Eq>of&uMYZ)Q6kZ9I*8C~~rc8c;-"
        "$FMYwZtN`_ex+YK7%b*?Yd053vQ*e5>2QJHI<0!YuKb9i6-I;`)-{Dwuq1(a#K!HH{oJ}QA~|qe-c-"
        "6nNzeU29@B-"
        "TfZaxhu@{U0Iz~<rfy?_9b6Z4z=MN#k74A8)1wckBA#I4@}*3rio)jW!@!nut#F#HWuYqZ#8ax%)>1)EWxE8^F};"
        "x3=wZQnKshz_5XNF9cwAKKWRhhI7Fakv6a)Qr&-7eLYA_o-H?|tr0H-"
        "=Ud`Eq<$z|R$zE<wLqkW+C;pD@~(f;oK;fIsKuX`Vk_fJmucTdo(RYFRmxGNTNhCniN3YX=LyKG5HN&phvpSng-"
        "=nR?N*;UT5hfyy7yp`BG*B+Lj2wnUc&#)ID<p#SyQ>9W7z{dZa-"
        "Teu#2`M<>CdroY)G)h|f5J&+xjSo2Z6e}?<+?N@DxY(Ze&LK9%Nsex_*lWgSM-xA`~ROG-"
        "u$vRI66LjcXW!DgOc|BQ|&+29`e!M5GcJ4&}Q383|G8}1ddhV<9C>3MmdhKx}AMXBx&I9*r^A5LBnF_*uhQ!8sDn"
        "?bp%r9KJcEM1IDwpXGFOlMsiaFOo_pN(Gkz}qtL#Bx#U=hERTLme@m@r50CeM*?$iz$cK}?V{y83^4H#P=_g%9Xt"
        "0Qj>(7-(PX2jvy7x}-Y2j#I?SNNX9ZkvG2=ha^xJBCiGnPePVga&&-u^4Vp-VEZz1ca%-l&*dKu3!^p*-"
        "PoLi;EpvA>{1ATBaM_=P$j79)VQVA~Ar37E{6lt6>P9H8sNnofS?uv%Ip++H$Mvfxmb;fw}$_*^kk3`gO7PKa#-"
        "*Z|xPwPp<?@t(2_x$M7tg<PRm^}9?KFIll<Qj;tq=LCHR2B)q+!-"
        "4<2=^f(C@?Ti=jhfY{#2;BgUp&Ob%G4<!CGhGo!1YGL9||B>Tmzko+Ga6ZUS3YA{b)Jhe>h9o;X@*f-"
        "TMcqzz6^2=8R|{<t%a}kh=h10Au?ndv9=lYIjSWy06gkVy^`rZehn1^0Z>cJnbc3aC=c=<5yJhOW&tCF1mIl@rRx"
        "kAS^1;y>LiGpX+<@H>NtI`j$&Aa)GpJkFFoYQC1{e%7Y<D=>Ae>nx@c&2xqD#4R(IuN+Q+rxYn95mZkj5H_R^PUi"
        "qe4@U+|kiQDC$|CWkPoE%DmL*R{B-p%jki|jIw=U1u?1}6ohNH{{@DB0z>9;-"
        "B(u|rS&)v89=a)|4F4zA?K;CZ;NeGV^iz{EDth{XM1)Q_cXjgBK{6Ihyv^gz=?PmZoKRU<)dB;Yl-"
        "6c3OeLE~7k7~zecChru#nawOp{6Y(iL3AX2T2lTGVpWxWfeK$Ni+M6at{aRn4$Ik`e?KRL=*yhC7hTGaw!~+;N+~"
        "hO;GDIE;grPW>N+Fr2$a`Lo?%zjTt<bA^U)PH>%`~nex1`I@=877cTlMqo%G6Al_GK&YNc(E!#*p&xsX-"
        "X`?1tDtZd}oMk%$Dv}(y4nBdN(N}2k)-"
        "M;LoKHbz>^%uw7``ZC&PyD3rJD!yFE<UkpXp!xv*gHNxJZ_4UzwRF$?Y;TDB1CUeCuvqjwwI3iwMW%TO}!2c9Pcy"
        "5Re4&gxn5vN_v55Mv-=p6Uv1?LF;6L5wul&^sux$X0-Y=FJAV;8zu(-cR%Ny?zVH0C;t357{VJ-"
        "Q^|qe0+vh%uLM>fa_44j}54LWG;{`Rn6^?6FjqM1VZhQOr+H7pSj%rojlIOS;dHI2|D6cac!?U*_v?p7+EaPhdU8"
        "G5r-"
        "^%>skGufC!5254%3D6kqF>#*2|UdPoX1tI;an;6%<~MAao=}KWpff3;h&={JG`p5MaA%Py8<GjvBW+Gf$tE}YQcx"
        "%uQS~{2l{lK%m)-"
        "$huFZUgG+KDBSQ6R?kOOPCKy=U%DR9JA~A^SC$_e(>KUUJaHmL~joZuy4#}H?m5(GKD@BN@23kCgB9&C<1M3h7OV"
        "g@MW$<xCDS4(<r{Hp<qJh4m1~KNzG?~*&6b*HY_+CjWx({29mhdRBzq8)+dNyIhBC`!d4t%bDNSaLd-"
        "3KbgadAE}9zAFx*UaRP=J93HTlb@9Tc&dir9j%-6OVE#@p6l<-"
        "S&C7ZV7znKH6{dtBtkA0Q_A$slNhsRvU}u9Dq{BGhgzlWZR^*CvErQ$^fdyjtn=}!7SEdmbO$PbSEj6%c#6+;gk*"
        "(4--wWaM(hN(x%0cC0=tY$wH4X@+H+hcEnpYJh4JzNr!_umHbPoCXW4s>X9l(=!-"
        ";(GT;O1S7fE{(4zZ<E9V__%I;@uYNa?|6$$gU)!uGWDft#Q7sV*Y@Y}D1JMO8nen?fYKMS!lvOsny)uIKG>*!kK%"
        "c+dSk*Pt4zDCSe`9WaomnB{#&=9yq{0D1yP&gWJxT{&5U(*-"
        "Ush})Zm>h@>^~^4}PRcOO_Ax2gaY>;)K>Sd|nop_2X`CXdrFNsnR)eW^2y@hWke5OhQp!W=43+?%LlCD>SAaj!#;"
        "l5FqEfp6de5ETx$LfwO;I~|dsIci(8|&+>HI04n~^*Vb;&n6wu~$_%Xr$lmUpVNj1p<z=z$cT)Wez3F(7AB*VDdD"
        "K#RN;b1WzmP)&yyPeQV5!~`lV@2k!OENsLJG`685|2E@|2%e?j%8q1wz*re9&#Y}d+{v8!7^oJoW>SnT)5ppEarF"
        "KweU){FsXB6@my4?n>~j~dM2EvntYgOE-"
        "B2~YhA9vZ2Ly)?xWoE|`L2~_D?8`eg;bwEso$`R3>tIcmKK|2_q80qJMZ5J3+kdZM^ahDMm3Pi55MlF-Th*Q?KdY"
        "ByGkR`6@s)YUQ??H7H`A?kgZPlTazj7HR$u&Q`gTGxJaf-t{wvlf4ZCvDFa12)fLL^eZ&$-"
        "2@;uHVqfJ#2cIJ$=I*uoC#uIYVA}imeN+6O{}*I;yd9b%&C(W?bWcVCBPR+)*NpYOgbR+(!bq%JwxNq6zAI|&$N{"
        "iY)P+Zqci2>Y6tV6XMyu3*4hZN8e8YP0c@p7m_yaBp>PNwG2>K8a*xC_wN#bUz@S%hCF8KU)Ev^z&3zoG3BK?Te)"
        "IUpfKRS;(Be-Xf^;@M{adV@R4^GK}ze^|7f;DF4n@~)mJZK=fcX-"
        "t5(vR%Qt73{2*TBU~r!p*v)<h3!TJGqi>vS@yWsO`{*+nlST<RtBacaGNaZ%Y{zY{&VxWF~4dbmS<H>d`o`#m$A("
        "7AAi8it4b61(Eo4!qxu+PdH<gCtw@lU$;C-"
        "+*khgl)WS8*u5$Imd|cKnYaDLZm_xJAD#ioL_^5*e)*O0=V$v;zAd)J-"
        "P$QFvV@!2Swt;P`2v9GW_nc;+wMATwHilML8WZ#7%1hQGuEAMwV!D;o)J-"
        "+c57_pkd;S65X<lYkevJ`8x*D;SMnfeVh^2NwaO@@)UWj0Glox00YB@6(^8<U))c<1Z}|FkyPPLAj*SGry$lLudp"
        "Z-"
        "&s!|uw@@deiGpPcGi6gugE1_jg<cWeE{9K%UR|cjl%8E6U>G0GvM*e`oKofKd5$FIlDYXZ#rL^13CSpT<YLl**4m"
        "&^2Slt4TKjTMeR`UsP9Aug`uA&Rs-Rh;StTqsWdtItcH%S8p?@w(m-"
        "1nuV@yB4JZ$U}^@8hvqUSL{jJN~36m^6cGc79+%oj2iT*AseQKTcUBpOhJ_h9fj)JF7V;y+N3ygcN4;~_zf{+koQ"
        "qiAaqdgoQY^{SO`Dv*p~Rzj68QZmYjgD$`%(Ac8%hYfUuLQ*YK*eK+JOK}?!+d?HqRIUq0Qrv=SVQb{6MoD_N=mT"
        "-5wkz{XqAFa*aDekCD8{FYfWIMW`%3rrXbLrg$9vl*11j!u86oz^Bvj_O#X(A{KP3|q<IgN}D!O753C{CS(YGC=G"
        "Eq|&6@SUq*>xFeQ0|Dhq7hQ@qaJ;s=(4k9GL>Picy>ci;^h={Bxf;r4Ok9kIi7MP23JQ{9*WDHJJT+J`E`Ce*owr"
        "SQRFtqa+Z<ah!R{jr#N)Z7t~sb99#3KiYm++stYAy2wMeIWG-ivVvnlUOnF-yYXZPrFsz@B?trU<!T_vIgqeN;Kr"
        "RP^r`7P#2J<<$HYQcGM?S{O#6Z73B`%<g3BPZwTNIrHMTv8@Yjb#X0WFfBRiU<8YF;CdmFrm+O5`pDgR)w^1~<EE"
        "XZRiByxxJHi!avk_-JRxK%01x<=-WYYd`&+i<iHV3;uAV-fggUH_LJWZPodKwM5DQQ4gq0ZD8CKY=KvA`MOMel;i"
        "JT;l7(rX9KG=gX^Qyjesrr8hvt3la5jx*NwX<WwG0?{><e()=yOL1P?<h?gY!Nq1JrQoU4=#rL{XFSLz*H$*;Pn)"
        "fz}`8A!_p%u>wGT>k~Uo-2e@JEP#X)*ku;da0-vAcq?Ohg-1(4^MH%c&co1<Zrn-"
        "3<@p(a))^seBX0FR%8ikm;F~r_$W^XK!5LVd&mD&-"
        "8j)2nlRP1%q&48p5B6v+`=@v$eQdp<};Ea06niDUnwTTNI3@)V3XZ}twiG|;2zc{rAn?&xJ#^a&Pg=LCa}t_HnK%"
        "3IR|TnueP3VK5YwYu7KqRic_|C_%l5m<7PtEK+=-"
        "V69sQa&z|G#={TMus;jDhD9=zXsxw`z%znW8s6|~mZY{DF8ds^F4R?J>3MI<s5`HSRQJ{SB+?tH`r(>YAf_fBlIf"
        "<_6a2nOF*dyZg{kY}HKX4wZegjJ)*Es+o@{YPjXs4UJQNmmg!KCbmLV*KXd=w-"
        ";o*DRSYI9?%%$YouYe{9;(~|e@;rqAy$M5#uU?d`3oKm1@O3cXu!7{PaMpf-e4yVKeoe)o*QwY_Ku>l-"
        "0vESLJSjxFvP=HknZXD%n=gNzDaxII{NM3+=s=1HR!duEzi!|7QMDeOmJFefNrWAa4`Y-"
        "!{ztW(hL`=KqI~o94cjm)GHo(UDJ5@BPT%Xsfw1T?aQ+|6jz&_-"
        "`s;XG;Z{F#d9!=Cs3QNA=E;B`|0Xqvh!y?sa4>9C_qn-"
        "!TK`IQ&%dRTnEOTyw%MbL;qn<^81nzXRWx^8R5i`<1du<61q37jYc)8c2;>xeCBvH|daCqP1SnkhS&gkn8m8UJKp"
        "l|=-"
        "c}ZcvrSL_Ks9XajkW`%AZ&C5XCiLhNzr`lFn>qp=4Jex6c$A;YM9O$&%yI!+pRgkqhS(G;YUd}hst{SYA|<NJcC2"
        "y>Zg*9mj#t;|dSq*^t8>}Hp?W^Gt{VxDq7oPdF6XLgu|1Qm)V(Bko6^rv<-"
        "#CmS3$EivI=2xRj$6fl#)iQ(xmNUG@6u7g{i32_3WAIgR1urY>>1Vvc}S-6WjJ^PG45^TB`-"
        "+@xht=egE{=L(J{4q=dlps+!G2g*GGWy5u_A>YNK!ph<b-`pO4eIzB`fGo4{xuWv$bNz6=6=yEt{`m5-"
        "AY$sG8w=PdvrQP)4r6w!oWar(U!WZquV3koPkf@**P9BNud#fr7r2p2w{7b*82YuO1?U=L}CnS#wl52ZBhU{R*7H"
        "7v$^9u$&&#7Y54XXNuf=KtHINetHoJ+&mt<;>ju+n*aS-aK!t_oc%fqV;4tD0^UtRzSr?7i~mG6;O-"
        "kZQmBTH~W{8rVv)B03^&FiBM`yc_4H71_>{HfcS(AaheRPrawE6$4DEP#}OURk<l+Rv-f+$?ZQeRykq9b`-"
        "n!=*oUgDlEQs{#MOu72>|`fH$n+6Jejl>Nw7daX^LQ<pUxrz8|ZmR~mysP8N*TL*Y40aC8m21?m8|c|0GOse<y2&"
        "H4)}P2Xivz$Ar}5oSVq8+kUx%Bm_u48!bbmXu1RI(a|MHBaMu+-"
        "LRLE04KxZonuO0~3Z@MkL1b`Sfl;zha)x)Ely?H&*6XsE|t$kH>=&5_SA-Jxp>%xayi%S!=;x5iq;me)06n0%rdm"
        "QL^7WG}is|TZPGf+t^r7(B5|sh+WwRM=ijjKi`4eW60SG>*q@PRVREEy7eI9X6?(e&}mNMX?CndzGGQ{Fzq(2CsB"
        ";;KjeDSwd@W$_++4!$`Iv3_(H!MKObya2@reK?Ha_WOIh(6_jG|{X~IbZ5U83ulLvhkR<r12CNm_%9Et3NzlJIcj"
        "~5DWd3|uW``5iUD!i;@K1qC;X4Ga^CATTJ-Nl7vM06c6)f@{deMhVUR}`UwHK4d=O0aSG+!&58$a|GzUVHK;4+wB"
        "p++wHP5g8dd3Y1FkW9bxSxL|lD(*?#&!%PmFCy<ZKqXT?&FhjZ*c-AgjdT${&-"
        "@sNf9`wy^e8P9aeC~Dv<=xk8g3r3&uuBUlRKT^ASfSIEbO^iQ28)jaj;jyq4%QXV07~g+>Ios9@z|S{VqRCt08PC"
        "NM}gSksB|Y6vZa?sW*A*K)J;XE2n~2AW?MRIE|X<=15T4fUO=xZG?fow{U&~n(uY5Ncz=5Q;pBAh&481Q2m9|&;2"
        "Wxg@VQaX74UeV>ei)^F$=BmSFKK&nRW)Mj)DmjL~D{<#Et~niMYUqzLY8-"
        "AyB80s%_O7S2^x9kje$+TgYQoh9qu>-kEee4m}G<tqb%8(`;&e)s%-"
        "*bdt4h<2yT)Hn98xWzeu{L$2e1DibNy6$_auyPOqGx#`4}HbohD9ae2gf~g+-"
        "+p;4&dnP~^LvqRS`l{b`!)$9aDJwH}FL!O%b~q@xi{X^BTQXz2R%|_!1*hyNP*!cAfn%=0n;{1YbSy+zo8f5Z<V4"
        "V}_+2_I!WWKe?VE4T8<?tY^sHe=sM?+6?)}fqU`MqwDQ%qBs(E>1gTHneYhV393v@O7$(IvEh@r!@*eSPal;Wj*v"
        "8pJmq9B!)fa)fLBMcQkK{W1(Pdais+McYbyvn=of6|BX*gnF?=byv-"
        "3ZGj1jJY(k=8Y<`LPH9kZaPWwnRka)p!6!IqYl-ufN_0q)#{7u_hW2?mgj^@!mYD7_PnQAr-"
        "9|117vPk;p%)92&}Ca<(7u+REbG|^`Y2DL9`&(;Wb^MHcoJ|rkStCCGUXxjr-H9n9#h>bj`~fApK-"
        "l4X~A$j?pritvzPjIR{a$n9US_&>_|>F2^vGS1}f1$vN|c5CEjw94op;>#pY>Onf*tJ_IA(dqQI>-brK4eD-~nC-"
        "_pV#O<*0z&l%osb7|o<}<L4;9juwK~SDX9v4?-${9709UxefT3IihT!}^aR%CS2FnvqQZ3TcoZ^`EYCn-NSHooML"
        "Y(iD(5$Q^N>%Dl&bBSTPVui%_gLuQP8NUm@j}aEY`%TCMh$o~Vviwi3+=Gr&^|cmoaVar~*tbB6C<{>P2T55;*G>"
        "&t&_^<%Ivpm9FcK$nK~r5~g&_`7SWp1mSTY&nr~_^n5@TJIyAn-JaCH^eJUn4dG=i#+%ylP}im?LGey|FzC=;MMN"
        "?qm0?}0Qc{X!n$?NB}K8X3N;LCT(Uo#?(^eD5mpy;~9AyO#J~ujR}gkh#L9pXT`-=-"
        "z=&VLgk3TL<KQj>^V4mh_dc34Od=A0z-wxt-"
        "p>ogZ{vq*C0#kne6uzSlAX*ahCkCu=L;gyefq?p{&J4bKreJ%QqMu4Iv@mhx2NYl-"
        "!iD6r<sMI}8k!EocCJ3z&y@l6G$8@b5z0)ZiPRZtC;+5DN#oFuAs0+U9i@@^g?JbeX|UBhU*U&Lr1%xwRA*s+4?c"
        "GolAd!>`9MSWK{U#|OP_YA8QCJ3t<pIwz#{T)Rb3lp&YzzA(*fgGoY@fT~n=hS1JFzc^?St|ISQgDAk`cX@~Y<EK"
        "8wVU&F`x9+z!t#xm=#aybga!vxR2hdK;EWYTp@|1nk4U28>F6t%bD>kNE5NNJ2xUPOXo_3OK`EAj+79OYy9!8A`B"
        ">St<o?G^T%tb;u}rkm5rNixfiAOHVdz*FXvzYP(!J;`INHN0u4&;$P$5jJrJ6^N3%#uns5HoZQyBUdhP{86BwUK-"
        "6-vm(LAZ>qh5>KWgF0DN)YH1>un~T_G<{!?MxA;i7*6E`?EvM9X*C46h=3ztWq9QtEFQ{Hj8UjHN5wh>^%-"
        "ZyFJ<gN005|BZ|>wG6l;ySD#gt9GHraBywN!2+K`g$p(Z*Aqfiezn+IJG$W`rI4ocHl>kTe~rCU)DASo^|@Bw34r"
        "irW<AAhiLQ9CvJz_>nwst8wLclTsEr3j%_r>4f%16(4fL|@q^ndSI_W7c<%QW^QZWkUJ)eRSy<^Mfvh2Rw{lSL;4"
        "BX&f)Ha?A(X9-Qnb$w$i>2R{`WM97O_QpUNu9(PQuP4`&8=`niJ(aEQal{on|EA<Rh1*q>ti_{ONDeCT-"
        "Z)qCX*Uo**1@|S=OO5Vv^Q#KI3^&$`CcagWmhBNsz6`i+t$(ZM2I8$wEwV^L4XphY9d$9su($DLY@vD>4P7a_EFs"
        "k^p;BR+UF1>c8b^)wt{=5-qC859_bg^LS9tJ*rMu5m`tgwmw}PZT$J+ZmYV_8iEE~xhwd-Ggd$9A%FI4SnVy}T~p"
        "Oe<&>I9vr?HlSOC|NM(3|%erHWaD1N?dBG4+Ys`9^aB{+o~?8B%~;cDjeGstK!&0U{h{H+E%oxx@5&4-"
        "PCT^vRr3#EhAZd2lPhI@jL5PM{6o_RmzKb4tnJxDo#wbfB_>8t)o1gT5-"
        "5l3;1>>O^vqJb<!L_!OC@gg;}$*crFN5+PS`qdDgQRws|^I<u~4$uEqJ4oqc|-"
        "qnT1CRn;{|jYN&mFNm^Ac?I&;<rOs_F6X6uF_j>^$qB=t#@HdsE2cy1s;UZ4oTnbNT?^z=S7M|DQwwb+-"
        "yroK%SqtgP_>*+l@+9(>KfIm0=w+=o2LcSnPDach4;kEOVpy3j9$zz4hT`Zkf5h!Lr@n}Srp&8?Ze=I{{7?#PwKa"
        "2x7{8#be#Zs6Jr^v!A+beak?l16MqIoGQFgDCX+Z?mIC0XS^#V}8Rb6a@)mfsq%5>J)!IA@kh<0pf{c2PxW+_DE+"
        "r68730}|f4cYnlpvRzycH%Y1@l}eqfvY1RF`Q`HqwIn!ljGW6zk9H26Ba!<PUGVqq6C0x<VxxB!!s|Z=glBc2vyN"
        "JkA$7y2m&))N5HExpb5G^$GUM^TKH1a~*})iNybudDgm3#)~W5Aa-2A%<BSEb*{M>yn0~<Dm`K-"
        "E}GrRSZ}f^22FvnD;S@KtP<BqxqLxGD5eQ?#Vt*#mlbh|%>eWZf`#b!EJ*_#8-"
        "C_*K8sH{c^Nrm;^n)M_%)klm(#oX6{vH&cR46V$p~mub`7_8Ejdpk-jtgeFXKuN*GtVM70?SBF-AE5wrp>2wc%4Y"
        "EPs*amnZa#r?n&gS3Z!L2P8dU4#2$pFZ}k^r(uSgy>3O~K*~jd0W}-"
        "GM`%0L%7!AU;jBp6qi=#wus={}w{c|@)4heC68zL@d_fFKNj@`t7LTe?;HM{z&tZ8n+mSdvJnd}p&S#kDL5WbK!n"
        "<_-DFR&sBXe;hFfEYB&Q_zG^GT#K^h`0nRQ!7S?tt2x>VUR7RQ>#yRto?K=KL&Ltyc{*-_uCEh4WD%a+?_Jj*To-"
        "3xq@!4fIU-XEGa5(Bhx3_}Sl5o}Ye!L4R6rc@~MkUm*dS18B4;&zcg+fEW}ajgb*(B0w2<SPjDaV!$LujVWL;ozY"
        "pZ+deO$PT*a@d4=L9fq%h2G^*R~os-i-rrbbDyb|5E61>g%0!@vItL0=e#d<mX>d-EZroU7KT5*ek$^IT7rD8Dv-"
        "(r&+Rq+hHYx-+U-"
        "si6iiApW!p=@`X&fW)ekZ^U@upYG4w3aov1e!N5s&y1X!x2vIQXpIye5*K0*<Iu(^6!dNVy@T?=ZFpAUd)A{cV?0"
        "-7A31V!YUeSJ%U5rG0hO9jARCvoVQH>47G(O727K0(`}Fd?l7ydX$s_BTzL0+abcFKe;2_YhC(+>GNR5^Q-"
        "vnuT+_jdCJ2ew$Qc;A3#vn=z)_|BM`mmKD6FkDoHJ^$v;4n49G>o-"
        "Sp0O7$Cv!JB2%@!q{|A)@Evo^s?}SB!d|hf52(#oR0I?zMPItQgF+oVmaDPuTi4Zz$79u$gK`tO>U}I|kVwXYX3l"
        "Q8{tj1jW#FL{_p$sKMk-cZ^M4c*blq1RMPZZ$we?BHx`-R_XG-"
        "@*o4LE)$AzGX^_Eo%5=9C)!8mV?mzb)KUW!RPOQs1614zrzQ8Lk<TT4JdgN90no9SS999J!l$Rw5_&HjelYp61+d"
        "k6dP_D}bY-TqNQqt$8w3H$t83LmHx_i{Fa<M@O92u}MS%3V!vV96-2T7}1g#?QLw&?}zo=S}kkPO93*l-"
        "Yfzaw@qjDwADYT<|RL0iXUm9=B?JgT4^V!emcz5#Rj}_t`Td&gcC68PLvioZ$!!-"
        "KvMCj$*KPg|&D+o2rF=o88rau^B1sH=f?9Bdobw%;wGO&J7u+^5J-"
        "E(J}oKAcbU74C39ON?bAIRC9!)99E;YdK~{y4%7s+Hjv6X2AXRWp^9Qo2N-"
        "6CgUl}*rWoF3(ga*<io1}?6jK#N6h{64v5m$y6&t7&ox4M2vr`Q&2Fdh|rmQ7f?v*Y%Oz%fAuk09eyz`5`T{osgC"
        "7Ly<F%ljz(Dcz&mH_80@xoPw&1qXAs_CfpNzbUeNi4$8jr#MvTRlOiK7fy354cRiYREUpxQD~ZvKUeMN0*nBhFRy"
        "KA&ls&p%MI{<ti;;g`rM@x_85GXdEM*vbs|>X|4}WWKkV=Pke$`eV;SnvS$^RsC1?lp1;=1nq2OZ^)B~C2%eN-"
        "=TR+Lr9A6lu3OM<`sI)C+?!+Pp4d(39kccbRv*La5K<Dcf3;b2&s3yNiqW#5!@?TYd}UQez5d?o<rE)dL16Ugt1>"
        "5)RCO)&w7Lx&Dz5pRil`lDpci~va6^F4jmK-OiS;vTKNw7?NS!SUR;?&zdrj*-"
        "O>4@H`vxnSx2%fKhW~+WGWiCguhko<oS=NDG;`=S1C-cL8m?Cwuh!RIA+tM#xk;<)Gtc?|0UXfS(fBa|00"
    ),
    "train_probe.py": (
        "ABzY8<;$aL0{^XBX>;2~w*Agu(Lw4x0X9f2u`_QtVX9<XiZ$^zlE&`?hlPMdlSB*xG!`wR(SM(FZ+8O?3KZ?cs<H"
        "_J-M8=7=PqbEj?=r4vnr3vTk#>!rc%5NlX#kkWt^qrf5k;fm-ARg;xZ58G)@=dG!IwuI?F!^_v*;&jsDbMkI5FIT"
        "uSjKyp?(XNG#(hl4-vv!%~Vhb9Eh;%VDo4#1rx4$=fO^<9-yDVIj*WPef@rb0aC&xF?>9-"
        "@`bW<}&;wW?8<@^3W4kaVYv`TA^vZ4)aK)aser?WC3FHJX?u(S$UTJE@!21r!tKfsVL=5DT=b1&!Gz9MucS<&OTx"
        "Bc(IT<$O!?ZM1@%>&B|EO=!+=Magp5WNrlL+AZaA$GA*Ro7xOT|=Q=B5W}_u%LRtZ1qzDpHQRlmbI6U$XfAo(I{G"
        "(^Won`3^DogP%0<kQS5woTADOjJy-"
        "@pun$YojzO+==%ERxoJEm{G=!I;PFoLq$k`9xSPRv5z$G8B<a;#FLNiZ7<n>yOWT@o$-"
        "D{p&a?m%dnLt89_nu5p=2XnhTf_{`M#`^&>0eDV77?HibAMKnQU9)6M{2j`*;7x;d?1o2`W&ZH>TNvzFw`r*7kt)"
        "c}iT`qH3EVCpMGs|(GLfG1IUw-WMUMZ`Ch@6RemaoE+^tD=r{X(w8oK)rwmA2-"
        "=I)u0JdPA~%Fw2r*5>92pSH?^M-zs`?uowuTU2h*|TCK~zGCg=HhU}h9ND&zx@;U-OI{UO-hS`4Yto>OM76sUzDg"
        "COcisZ1oUCUuTRMW^SIB0bEfBP?&Vfo94%l_YMS|50tSzmptIq3ZwE*4O;ya`upd}1rZPvNC(im2AcckA1735_z5"
        "fH&h{eG3O%!DSNR{Nq}t`}E(@;CcTqFZyRGG+)h1NBrwwnnls=uKoUeod@hb;$U!ah#Of|uB%dQ`QS5%2CHQ7dp3"
        "n(+vLn97S7kG-Tz93t7-Mv4Uw$<-G@sAS79E9aANU8&jGCV;uT;AdnsSQzY1x-"
        "XN9@S!!*iPJq8@umiD%O@+zK{zIYQC`2YQy7z-"
        "0$TvjktPmN#4YwWyKni=k^<ICfVlgr@z<m1`J+52}F*jl{pFKE{@v@^W=;^X=8+qYpF0<`>Eoc5pI<3X*>fE4ay)"
        "ijk+kjtx>u)yo}z8A0LJOoa`k)S&Rws0qztKAn~L4V;CE=FDilz)9HURP6JROy0uUGLS&>G40`Tn1W%3o#O7X6&n"
        "s>nLHq7w_I*o(!>4Trf9PA=Ex);0%RB+sMJAq*|rIbsF>TI|}O^Z=gvXE4)a<6&WWKX_ofo4a`CysVP(ige)_FWr"
        "DkacwS9NDBu=Ib}bGJW5BZ664Q!O93DJ-"
        "W@5oWBv}{*w36##iED8MB#Q{E^%{kMrwE{2RThdh=TAWgR5j^AO=s`^e)94%xOo51^Oq;kx|2vCul(y@_v`rQSmQ"
        "2_f1yFO-^0gY|Ngi8BX80;O)7!TzcGCTToJ@YU=ZAerYq@-"
        "4MZRE)*A!JCZ6d3ET#yh3JtHI0Nhsdya6ubwd)O%>{{lo$3t>iR(Xn%aVqZCn?oq}h&4UiSo0prB=#C#p#O%nnlD"
        "!2O#oK{V+IYzaavBm%)2a=%p-%txaM1-2alR4)`3ZHKpVSIioKlyPII*<A}eqX2-"
        "k=fLr{&u8iJT}eY3~IfO~j6QgeAV*BLrWO)*53smnt=@soHytg#4=i)82{srV$%v)pZ=)ZBRiDQvdH9sU1Zem@W="
        "H@Kqg$Jv;(_q9=dPxDEWe3g6n!c6l;J&&D7&w;2c&-"
        "eiPS67Gi)lq%*Lw)sZq7)U;R9k<pwd_bOz6Gic7LPWtxho(LQP1mXI64I!V9|<P0@wzK$o3+QI0JEE;H(5<lnVY<"
        "F#rZv3gI;Vg@vX^z)*WN05$~N(@wxAC?NqhX{APG_-58*-oA#%*pNeF!Wr{5@*1%W*K3)Y%-"
        "ew9Ua^7ZR|Nq)v*#$UV`6y93dW9bqhg>22S9aMC?gxe5O_E{6f@ePZil%&a$H0Nh>8(Jcw*dH6ZvvKz9W0w3-"
        "^u<eD6WZ0+h8dF1E#;rU}p9bm-$ctm+ss6nDf<$I#RGh669}73h3VEj-lg4u3Lo{yhAt78KWwWB<H2XozYDB8d$w"
        ")z8?Gq2fX&*oQ7MoP~4|JY6%?=UtB?$uo{fix<AAchDHSW2}@)mY@g<O-"
        "I%uB`UEIJs6+>sEy>+&%qfDLHs9l6d*$8BG|_58nlNkEunORlUK67srVVN-$m{r5p6{dvwY(jHWC=L`;X&!LQ-va"
        "(D26+8_I?)tqn$2P)l^8W5D%gR;8t`GV|~{-"
        "~dGG(hrzUzQK{#8GUl4PsLA45)njKD>YHyU+37K?%WY#tRZP49{4N5&K;SP1@i8NGVmSKyl<-"
        "6mP5{+|BwKfXxO|LN*FkB6tmM9@dhj8N&!_Qz_aI`ci+Sg&G$$gaBjpLG#2gR{=4tQ{~w>fJA3!b@S!AR{yd&m6g"
        "mzX&NufGvELYZbk|%X`d~Yhvn2??+m@Wnr?!+`w2o(G6()`Rj8KjI-gx-q#0ahPiq>|qbA~!Cb05zZIs-"
        "{9@sN`p3_Yce#2054b-sxC+xjJS_HJ4xs$DWrj(@q7*d-yN#OvepSK{5tFUOZ>A5SjC^p>onib|Sn8Zux2Va3-"
        "$rJux~)aJd)X5q9-"
        "!u%H8Gw!M83#SbIB95e(0}yE^*iD#$IF~SmTBpk8P)Ck*9xudRq>7w9C5h@pG)<xaYTYldvwdnt$bnJH_EZVm)I|"
        "D#iK$@ZcjQn(`a8vRN-cH=_^t$Ac~6<&Hrqq<53DU%4-"
        "|{H@zf4lT?_bBr?Gl)S*IhKZ?82S8@Di61Z<)lh!pBtHHD|3U*62*x<o!lA5_kCFz>VsKzuYeV2zC%WEy8;#T+Zk"
        "=djajV1L;7c=L!gMT?WR6c<)Zvh~}Y((TmU7i4=6vc66=Z;6}T@zYTyqT>lQOWh<5sauZofB@m|&WO4-"
        "vhE0jo5MN+vD<_e0)N7KLajO`>kQCG(Dgdv@1}1dg%xs0IcJ)E4u|5!o0Efs!xke}K&f4IqP;-"
        "}5iv(XCL^G@B*@;LBW)%;{Czw$11IK@b;}Uj9_B2rS|NGaYHxRhAOojQ+o<gAjygfpVhsvzBD!&k2rljI1Fz1iyt"
        "$_$NIE2=ZFTZIU2x>7snl`ilG?++{g(dro6u{CFiEl*cf7+{o)v{zkh+Kjwj2PHTN7r&PpXz#Cn2_nYQYJ`zR2cQ"
        "(sG?uNrY^*<QRf@Lb}nV3l_Rot@W%@&x;in!2k-d;DGO`Hy1Oeg9~oRNL6hml-"
        "W?OuiLK$)@FJSiluqDiivwWrs&#PYXH^rNLT==O~$!|8Nv^zw}H~lkQ<C+ZY?yy9IkkGUn5;i=wa+x)2>M%!!I>*"
        "xmw}lm@{|JY}ME#_*ofJMq#te4?b6TQrOIBz}0Nzas`b=)HiN}a6ZG(=!U~q!%<wyRbitLSCE*RiYIDuO!36NVyG"
        "UaxEO;dElnGW=XsVs4I4%>H3Hd1GukJvOcGx#;dgU51TWs_<XSB=P>G%Ec^eWA3QTcx>KYbubeUIDr@A0<px!Ml0"
        "WTKmpLOcn&=_vY)I1u;;(u5N%`I;-K7`Sqjzj}>4fVc#J65Ck`zI;a+r#4*TIMsRQB`Q^-"
        "fv9QsGb(1wH3)Z=KVafOv%6wuoxKl!ChZ`ZXp+u(110q;v@>p%ff(SvN9Ly;ub#f-"
        "KvmHPF<(PWEu5*7OsP}%uRTIEZLrhNtn{MdqAX+6frOXcb^^ky7bCQ%2)`xgBrRwChy41{YILN_TN*nl7KRTO@ov"
        "^p;c<QWa#2vvNXB*Ijgb&@Vc!)P=mV%JicDaoUpk;1Ki{kQc+aM87kW#Iho-RXUC@V6XlG%Q&dlS#!8_v05g~BT?"
        "&<Y3Rz24ODGVYZ^pT($_eI`NVsa_Cu9${r-1bIku;DVKa6SWxs@l%nMxDMwVHs9vh!g-"
        "bbK(`o=2j>NlYeLw}qRI@Myygzg3pg6#cZ`y*NESdvo&2BsY)dcV)QXMrgS-GVVjh{$V3zt$*6vW$U)iif}(^-"
        "8VrU55`zvq9MI(60P=r?RDwzVTrt5eSeb2)?1SfZYh6m+;F31cwRxJE8R3i4bvQOAU0VR<Pm)_TS{aI*4t2aw}F*"
        "?8sw=L*wtU^SselL=~yKLq{Ns~lM3j8WXo;zz#Y+qS}~S|u@k>`wzUaT9Uk}vK~{JwHh`uT8gg#es{Czm&L1wJsn"
        ">|`y=Wiq5N=&~dE99rDACzg>paFhz8Q#LDfaMNJc}Ur6X!H>rBQPp14xOGimYTLv!DvYs%4-"
        "?6y?C~Qf@)|*7l<K#RDvTk}^rdAYu6(5SR4W_PhoT5Gx;{JhAyAZP!mdWE$!AnO69%ZzI8P48_9Hs~X@QB5p&s$v"
        "U!m*)3gc8tsP2q@CgfdMdWFd*E}f)#kmON|@pNq2;7&&Y&%Vn|TG@^sNCKRF$(+0w<$pZA997P0K0yp6<D-"
        "869;Lp8K|GA)3!sQOmo}RZz6!<cpKj_va_@v_2(yH}pE9UU9!>Hiw_*^d<maY0+C_S}r+D!uH6++hSnD0X1UR)ZV"
        "8it!X=N_+M>6v#4bOto-"
        "#P)TVDIgl%1uE}u4oI{+N6ReyP~!lVn@^$cByKR(5vzMiv9l1Z<tY}fd#i}qS+cJutssQw;eKCIuHi6s5Kg?4vF;"
        "dMJgr^K}~d`sq*zkTx;`;>kYJi45>Qf53fZ-"
        "@)H;;23)GdRu{6`ei#z)za)V<d}N9&;u$a?BY;B#B{Fpt^i`Vz8hSO+&G=j|%$wD<4Mk>KDAU&>)PWAk=HSjy~Sx"
        "_(B)CqwNQse0p^%NBH(AL0;4%cyypAKGq2lOPQ=k&ILAdVj2oeh!3wJ$MOc^Y>{R;@&N!^ea<Q_2yC6*3>6kfT(H"
        "!_?BeNV`|zC2oa!pKP9x4`NL_Wfne%vS)8W%}d)7g*J>go%(!|w~VR(lH=>R13X4?=|jcqR<8B|97h|$<Qa#k`-"
        "oyntw>tkycX*$5B3D1$A?X>9WhjXD%Fp{o1Pcc3&UaGqEwgI0v9`)!{b<ECIjCJCUEqHXGkKKK#cbgQ{Ch9vNf<3"
        "=^zRUaLPG%qbD0aHimmhQ4q3ZhW1W<COAgCy@=>i~tban}G97WcFV%2Z$Q&!m5E!TqIoKk_-"
        "E@OB3cXQ^@Qu_~I4lCwJZ+&tRl~5gdgnNKEUC<GOV#iL~D55N84xb-<1<bt-"
        "Z<Hq16$+F{6)Q5FEp?v(y2ECXO<BLoY=M1Px!ZWVD0JuOf6x(<B)hg;VWVk*gbWC(N}A+$r*}trwqDcA)uwsFXW%"
        "Jiw$JfCE+W-TmcgDKeIbT$K^>>TvuRxZ0nIMwL79D$skL-"
        "g3}kv0=UJ*=;=Dc$F5mxp^3M4Rym);onC#!^L_HF@DWA~K^tn?-"
        "4<+9fx%^HAyXuJakV2`5OXZH(%zdhxk;Yue88WJRb3i<O0*nOa4-&a>b@rt&RtLzDaH+54-"
        "l#JfH<TvQ;DLH>Iw!uv1@et~#Wv|=nd-o1t}0*nU|_H5$2jKa8)s=uCpT5f{|!<*JEI-"
        "nVX^y(ctJG;Ib+?pAQiIyIA3LMO~}x)?)iHj@>jLf-"
        "NG9T2Ik#$XU`EbZENV#-?%V3YhH18Eo)R<51%wX)@mt@cy|4@8MT3aYTU-nW;E?LHH5Bwt0?HgnGyGi)WTb!NRjY"
        "5?eLabz0p%$Wkmc74Z+Ro2j_M+4(Yge)`=jy9NAY>P4}iRTH|W2JX3Ql@~m1Hx*gu?erc&%zb9#4G%2K4-"
        "G0Sq_X||NS)u#XdiwywrY~)=1|KBRQIYLv6rcv%p|?Frl~{q|Y1B0O8yj`m=~!_N3*9Nf?>o;{b-"
        "ljbVkckCrY)g(Y4(;;*h6BpQ4%^zKF_5TFF)2s{ANI*5GtTzj-b*;M65k-"
        "P;Aoa&xBnu66Ajqr0{HbGEd@i?OxI6latm;_YIV&B4yP5(}>1Xm>Qpd88y^>>uexKj~Zq-"
        "o)jZnFl&peg2cEGe`%hYh^QW$Zx(4Q;Oe!lI|c<BDF=*;n=foidXHTOC}9+hx|VquSxteVflq%k`)#D%%381pucU"
        "%@RbXgttlygqW^k`Om?5Q;ZZ~A9A0gVm<)T72k*MowOIYN&t<j@%nQW;bpzfy=1k`5;0!LwqYC81(3(;&KD(E-"
        ">00"
    ),
    "benchmark.py": (
        "ABzY8<;$aL0{^vI>vG#jcK*+&=*3hbU<`s6k7sAOp{rzDo>fMc6<O=l7Dt6`5={~o2w>5mBraE}JVf3h?~zBzljJ"
        "+yjVmciGx4ZwiEMPAK7G!2t_{nwI&VZgTdsI^!<IaYg_LZbWGr6_7RKp1?=E;Qn9TX?hS_HW)_u*+hK|=6|C*o92"
        "f^h!6OxHrk!{#4iRa;Bo$)+OVupWuIN&*#A_oKP<M|0&C4q=ol<<J@IAEDblPs5=X_DkJ&v>fI1ULuroQv$1N77|"
        "eG2?3~Sejsv37Lm097WPLoXy1@Tdw0E6Cjw}$qvs1i<3|auhV&3XG?<oD&;iM=265X#1zI0B_YXIf}IU|XG11u3C"
        "`t=I*fgbp>7gK8&>=2G8}x)!Qx`gv%r=P<53a|J%6}o{xS@3rY=Me1*BOr6}1&cA(2?{*~T#|pdK(6bf-"
        "~*haWFVVXwzZfyd|Xu*>UlzRa9D0Uq7)jl}NGUIJ!Gr*odLV9lfMjo6U9SO^ua!aNtjh{=#7pD!_1KuAji%S)wp;"
        "w0`?#I@MnlIW3SX1tqZ-8jkFG|Xui9xcQ)<KYal-"
        "*iaJIelh%!b;w8jCFwN^DqubHSfFqSB}R{b1(ulV5lpx5{Ovx+YsmuWoMRvD{wL0uq$BW9r*Z3Y%Y>0oNWkrKuRu"
        "qa+TZ&Kbg;?Fcw})Ph>850Fb=XAeGFfslBC$!1_98GL6EVPzHVe?|=Rmi|P0bKn%2D;VdyYGDr!8NI|6s{jSoy8^"
        "&M6OruVb)w=ouRV|l1>3!j0G|dFR>CPf9WjKc@l<BC+E(_-"
        "Xija_zUKoia65<bk=$$9|sUpqnsffb`j163M12GpdOoWULhW-BHva}OTAX{U4F!-"
        "VOcFFS}FRr@(T5@oqI0m0Ef;1Ae{;ILQ^JmEyg4sXu#Uc{wyo~)W-Q-"
        "I!JT1Hq3ANkRCT{)Porrt%Yv{e|{{Bt(6w=Ptv)p1ocS^(PYFkjh{l8(dzlyvs$utV5co^}G$RryK-NE<nu<s7PY"
        "pjh1zS>JN3kS#{k>k@|Af_VAdH42ZcM6?$+sf$P4&73e7pFgx0k>EZnO}IV;j2DIg7qr(jTxxJnlIi=-gYeb-"
        "A=e7KgM{rfOnCi_)gEw$3%AKV1?zIlwfT}&qA4(t7B}lVO+8}?dZvAm<mE`G2MQ5e0BWk<jTK1`F#56^yB#_mz@?"
        "Tdna=J;liwPJ8bXI=gZ>{A9xIfW-fye$&!6#u`YIuV-"
        "fh7xD6#pLGzt&Ac3#-17cN-O0|K`njYHNKiU1roSRQ0;VLWEpW*~`(j|{`$f)kh;3zH-lGuD58_P@P+PQ1x$wYlK"
        "8>_G+L8_q4?m_?>c2Dt%w8Z0$iCD09g9-"
        "2J3It}$$gBHW3_eaGZAXP>U}FNCxz^SOoLv>Xhd4{aN1Hh6lDESF5bMElATp28NvkuFud|p<EECQwmsuuK(MJ_QO"
        "axNwIMrwsR;+8lp=8+jczZTqAa3NqQaTs`yIvgdEaMw|A2z=e&>ADV00kTs-"
        "4UBZ3Aw^2?N)x*t^#q)j3`l6BuiPn6ElTiw&L<ed258*%2gE@u+utT2ref0BPtN3^N&|2BLWR(LEeBu2>$|x5E0^"
        "99M#%mG|yvKyWvw2(;@Wa^U393*!~bIlP9C7qST0_?2$-"
        "H5laI@d7PYF3kT}qq9~2PhKkl*vW^ftk&%=(1!FL==vl#7k*Nh__Ui(&SLjatMf?M@*m%rJ%#KRD7&xZ`_Ig}mW@"
        "p*(v1LPARw8MikNk$6^K%tPk$;Ld<vr%Ivk57e{e#(d$)uXd{u!8S?(aDJ>DLVJQR;0{+SoaAU-"
        "p?tYjKigNoLQjb$k;icePkuAa;vAf0sR2zk#PWSru4bz?Eg25wl|?*{*W0B6G-"
        "41WbnCZrERqca?uFVjX0#k(8qmz`jv_TdzZiczbrr#J!lU6-"
        "ZN_FCAAqcYqHLdktTni50RlSqmZL1whFFuJ8Z~iv`dr?xC9apZ|X8{04sBrvvyVP4sDFd&X0fO{suiNTCpdUZ4ln"
        "tU$7HW7IB@VLh6E!k4Q|c5Km}mRkdp4)fzy*x#3D93XE1tauBgCq;xOcE;m{uvcMBhlJ8aYzNYD%w&UOdy-AS)qQ"
        "SVD<_?idkEyUOFmtBbbEr5&&I5XPeo*1JB@jcV?vUaZJAX2&7}J43;W4D{%Z*Rkp!;x^9(+Ijdn;QG@rDi_1)4>M"
        ">|Os=@8)3wPZ>^lHG=!S;%sQ#cZo&%IaCVSh1WxR^b#8)Tq_an<deD6}v^EmLM>x)Q%ilzz{=}KU1v(mDZUuT!!F"
        "3M<figBuz!2BZ*;XT!YepyexbX;Ysm$?RZggCo<dd;Bb&aQ3|N}wj74#g7qKMLIa0&P%G)VX8#605yrLM)Ub$v_e"
        "P0E_YK;`+{iRiOr_4*`N@yRSErv(D7wOl>#7QhHW|yMKpvn6k=l$3KYs+0d>!RSZc){ib)=8XsF&X*Jp>SeB5yEw"
        "srx8IPVgBySFISyG#Gk!$S(Z|UcCp9iA9oaJa!x*|4<an2GoYZ?ldFD|DYM)_nP1We$kBiii%GWL%O@R>BnEla-i"
        "Mk_^#dJ*)l-"
        "SHdSmjd;|8naYo_iF_!EGD)w!lT&9vaK9)vr_;wo036y(rSmMQUw8@G4nMiYXqW*y1KIW~4W{Hn#0BUXxkj5ynFU"
        "=k~HY#96j;O&EZy!1Z-t{oVqPMHIZwPX~^L$cB+Fz>QPr1Is^3?9@1u2qj-CNM^#*aBv%b6h+c+`MpIlKO?_$lQv"
        "QNOS0VA@}n)7pBWTpPv*mlh{~<0JOw?4;ixG^u73*ya{vlTyvsM!;M3=Yh@Pho~*L6%SU+Gv~SmrPFB|1Bh~fCks"
        ">CfQ2$jp4N0^)~dgg5uTOv)KE2ZKW{4k3fPtouNF8D%(S4e?P3APMUFu^4`#JAIJcC=Z%bhoCu%xP`0BrlERlA#i"
        "OT}=)#H#_VRdhs=V{ZA7A-"
        "FJXp3vdn_hhUbh_7@9`sYcC{=j6@m9+fsHOOuB@55s<o}f|Tz6V=v4%Z7H&%DCYlu(SW~c5bVbQr$0DZJ;_Z~+I5"
        "C^uN_z1?}7!N?~^5n<UPgkhY$86iF=hiBZv_^X}c`g1b;c3o1n3tNRrJ?yIQyR6ChMhf9qqI?F5N_we*hqP&;?F{"
        "RNzS^_jEQ}kFrr%)9COg`_g%)LbjeL)1%rJL<$h^g7b2Tcp8<tbbzSrJRH>UY)l#rmf~zJ9XZ_xQshu3JR?(Bhi4"
        "}*+-2P5gt2Rc|<46<T#y73Sc%id7z%fWxo{1bj#_hf-qJw(^TD<V+_6QzH+I_d$7Iqf?U5ssg_}T-"
        "56XKtcOk)$!y7p+q=J%l-"
        "5A>8Maq(F5k(MG+CkM195G4Cn3zGHN&}DkS9<XjT>NN93eb6W=&%6u^M@KcRZU>$NvRYse`?zd1d&k*gy#f;#^ew"
        "XkA!o1*0@v6&ZQuHp<-"
        "d_AM`j!ZJ~uRM%e3#|kc@E0k2msNrfde^9wnw46Ln&>PQU8z5BsLw{~T)iKA=X9WKyl$?*W%0O2_1Lrh=IZ1$BV~"
        "e@`U@a;*?G1h62yg~yI+mkmeOVNPm{U_L7xh-<cdOIM9K-KZ@hv-JUj#a+g)IvuuJ@ov%C3-q-"
        "lGnXU974X@BQBAR$M#4I*FqIU_C91Fe+~~&ZfupE)Ty1UN`{C7d*AiMAOJDZuOAm?RtZK+LbbQpjVLdW6(E%w`S3"
        "q?ozp82Z(X~aYP)B_uP_+HLyX(*QAM#22sNGXN3Zq9CFXw)q+=#fgGLfE$Z^I1PkP69vdhcI-"
        "{ORPJobz*F`KR|xk^Cd_*a%3Rk`{7Z+84Bd$y;{I519r<wlMa;n}(zfKGVKU<~XMhPgJ5gTafDp1?3othO`}B*i="
        "`AV`fiQMfRX<V@0V7P4>!Jp325-"
        "%S8f$sI_XQ)vQ&zHP`B<0SVp23+;1|9Z^bsulKyK_Ee8s8{U^2R`fNQlDIyX&eN?o>o8Ic`triiu30;K!OqS;;I}"
        "ev$MZZRF`5m=9=}1XlGrF(>GP@TcdS@a-"
        "z)tW0MZYOZ*HxoAlIVKF|LlZ_qiPFKh?uhyyNmydnL7jHDUF=wzdW!vvX~vv4?V8mHQhPs@1on^_d8>Jfdr`YBJK"
        "LHcu@|t-)$G)p<w_6F9B$6(FsjnCyC)5o-"
        "4lDABPqPQA5U1EmI5g&xwnmi^ExS2&$|*{7o=9*(zk)8>6Qe_;PGNFHzN1oRj^t=D^V3-D7x2-"
        "7FC$q|9(NOurt1pSJ{z$-Fh(79Ik5UTzlSElO7vaFD61UZy$YM?AMh%!-"
        "}1P!AON&_qWam&QY>DQwMPy`9P$p4kwqaB=j1!AU!vX+yz3+IWv3Dav<T)PzS6HqgAO9YGJxA;LsLR46boeKQtcz"
        "ZNH`u6w3ho56p^NkFN>QRl@P9Mh9JR4J=B1P1QsY2Y>>SE|4t9QG0`xcKL)Kmq!4r`SK2PM;JLnx@&TY9qbfE3%o"
        "V4BD<4{wEZ3RtQ21D(9L+YA+-=}^y@ucN3@BvSpv<7%S1g&QC0S)j~_YI_qjLs#j904iccIZD~gs^-"
        "akR4W4)HA&7@o3k<*730;Krf}22B&6<?Z0hJ627?ZCU!(p~Sel7|3Q?p7^d=k<Ch9ttLBz|}s6ASgsP!&xd9)_qh"
        "cX*pp8n9QKh>KX-vI^jqMM6s#pdC?<28s72b#~u%O`em*ol=VIfp-"
        "7!hEE4{fy3rD&1%$k3^Q6mHsSQ$2r!sh8y2$y^^OiJdJj?^651O&28Q9J*EMWvqOa1fy4fZ4PWiSbJJ)Poq%n_7l"
        "Vgh9nmebX}z}trzv>m&-"
        "iR9>>9rGm8HpV<uAX#tPxT#(gej@6xACwsvp*P0mQ+Pt4r1w>PA%rHB#orRbBj4uS}SC7)bmmkH}2PB&dfSBr|f("
        "@uCJC<fIe}w(4z@_WLLF>Ivydzhd$nyfg!Q`E{X;p}a_M-"
        "}cb`JY5Owysz`nG;zgJ@nQ!x!oa*2=3*sxI#yK66BulJLtq)u3j$`PV;osy!MwGg|Kx&r&kp}_Xhk0H+2Zhul%gi"
        "i(qk)rZ$lUO`~q9Id8cXf+O#=M%i|qtK6P2>uj;fkI$3)K#U*)LTNjrqzS{){I_a^s>)v(YhA*|@{LqH|r#39k@{"
        "A2D`&W4Wm*Eg8)YZi$(ybKf)=Q*YldTqm`sQx6EYz24#JN0$x5(2M^Z3DGJFRw|g1skt^NQZQPH*0%Hz#`Y^hFMO"
        "Eze`puA-"
        "}IUg1y(&(l)TB)n3cN_9${PR%zJxoWLSZQ8;w3XY8=v0!ey*Yd5Rlpit8ycNcQxX0JfE$*LHAJpE!(L4LyhXwDTn"
        "8wr$aV5~Yw^hhRxc~mqb;EL<WvOtJdZ7d)Y!z1wTpA>YPm$DN(=cs97Z&KA`AA97%S0OSnXr*T(k&aaoXKeTLw`>"
        "+eK1Ng!GkXrnNU3x?a=KNpJhpx-$EG+q3)-"
        "v`w*2dOcVT4X*^ObR>qNiDeR{|fB0~G`4?uV6%|y&+L<~#8Eu*C9htdDFqS@yWqYKT92w);9>IK$Mz6nDpWm0CS?"
        "nVV#P3)X{T_8aLDxTVf$a)efviD0#!8Lr7^^E#Q-"
        "j&OJJ;YbkOgy<Q7eP~URj{BMg0*8JZO(z1sEmT^r=Wu51NS*cLJ>2?Kx2K9rPTFI|{X9y3a)NK3_Ji<_^5i<gNEE"
        "oaO(XAtGh=e2GJaA_~;C_Lwg9?b5I&{cBH0xR%Gi^X_Q*QmBez?=xCoQF8WFHWwo6k|xaCx!u=n+dft)mIKL82O{"
        "%TU&8m*>vO(OZFAo@ug&QmdguQDJnWBQAu|8~"
    ),
    "tests/smoke_offline.py": (
        "ABzY8<;$aL0{`uO>w4Qpmf(LrMJ>GF21t_-NlCsa&FsjMoM>9MHMWw@e2NAQ5=9ab2p|9`iR0Gy?L+K4%<p}Ld6a"
        "#UJ(mJdxR9c3rMt7cnQ4mz3w1el&Z%=R!!SDUr_;a>rAXu~k!k8jp~z&KrD7T-"
        "BAZJwi56pM;EC9eB{em}NPKtxLs!7xMdZmqc+qVbM6Q=wcIU$~JP;yYW%DT9<-T^(MRYBlh=;P{Ri|?l-"
        "N+<85I=r6d@H<c6-yCEfj?P^KZu1~M9HeRaAUD>v$-"
        "%A(c~H?0Ar?BSBxWg<|XblOTQ9_=cgSv@ZD6VU2&VZaqNe)t~hg7GU@G#G;=e5k_vO;hHkRjfmO=8onMyTObVEQ="
        "T9>1(p}CLGQ_q~*zLHXM=Ot#$sDGixLK5Zl>#8bEQta!4We6NPF+9fO@b&z$iOUNcpjrC@1}kr#sN&a+nLK{;-"
        "@$VHR=oo31^nL^<fohwj7H9=bGA`&IOD)m+p-"
        "(6Cp#dmqk7JBW_@Q9!*V{iF5;TEMK2|xNybUpey1e8cP9l^uwLhy^%Y(4Fa0F9cnvqmnr-"
        "?JA2y|fqx^#ZjZ);C3`-sUEI2<kau#j%wQoNOg5YePu|ENiV-B()zSG69h&aPMHHO99rgyh`)_-"
        "vA%JE%$pmzO(0cJ2p$*gaL-D`=$Nv<`5-@4*W(+Ur=1=Zy7D!rn=U;ARIJEbB@KOwu`EYW0{Px7|7=Vx+e-"
        "TGXCW2@-gURGyqcs1N$ox~f9K-"
        "r2fVRbxRq+vVs`#=D{R~mDGfkoe?N{KBh5GRvzIHnBs*OL`ewfN6Gy7dwPh#SarsKetO2@HmpphuJk){Q06M&EUV"
        "_6+FU)%FjcN|DF|9<r0^y2jB@C*=pV0AhjPfmpcV`Od+IG&7Qi)A=jIfx6XX^Gyq;$0NVgN}gz03c^FBlxCEKa&J"
        "i+KYdeNd(XR#OuKnvK1_9a_!D!DpcRn1C+u(0IgD~h#Gb}nfPf=Y&&tVMCzU)EyFM}Oo8f==wR`YaK*w0mH?Z8{b"
        "WcFJAi6o3cO(fIJ=Wx2hvSKu~?=V^{{ZSr8e7T2=fgQ9Kv+P6o5CUu8@=fV`1lEI5)=(z%wB3J2CfZrtTyQR=7mq"
        "D&hkoGwfO7CO)hYfG(CmdeqzPT!w(L#I9EK6K^bz`wd_o^m2=c=)-&C6p?x+VFU#D7@?#9&5KM{40-"
        "%7$0S_15YJ$Rzq$wF&0c>%P2}A~#+f*!RwqdkCFQI9&WN$lej9nqKwiLS)1Y4rt5Y<c1a6uN=NOxsfO1yZ3;sv=;"
        "v_Oo9LG#$Fs=QL|0Ob8!Zu8~bNdrEyEi)3+1NmcZZ>!hvr>Z@>IuxI+H%}%I$qb7p6?Fpz3vVhEt$>d?K+hO;yD7"
        ";Fo}rUnqRxg3^?l7Utizir`nQXvpz0kgnG)S!9Vc;emIptjT1@T3FPCgzX0{-"
        "`(14HRNz4L&IG83NEn}7_OC2@is;R=Sqp#FzSG!0T$nixH|$*4X?cpT)i<%W#!($~wdP^u%n~>en(gZNcR|G81oX"
        "s@S6?B;CGM){#y$!Jz$f|G;`1jJfB6d!$DRD;FGQ1-"
        "u5wlZM95?%y>Ec@=>$ZE7A=85nSrF07yt5?oVRliHi;Y#ptzjip$LOb5;vXGCZ)ipLu4E2wI9>DROt&kxb6WP0$%"
        "eYb3_~2BhP{uMJT1m=b4*ji9d#85g-Yq4u?1)O%1-"
        "hU<5CJs{QOZDCWQ{9S7PNeH;Go4<rrsaLf`1Cri&Q*u_U!aUkEh3z-"
        "5}mu3}HQ)fIKJa<y20O^eacQN*mF}Xo1yOqWuN;$yn;Jlees-"
        "5^6n&Ro!x2kQi9i03=pjHS&>&*?CY_~oS_XdO@q?AolP+d-"
        "<WtbK1`qega5oarB;)1+YG{Hk~?F1)o?2i4w&sLRHz37Vl^{WD01z{tD^Fx1W3y|}E!lCN0XgUJU__Y}HhkL-"
        "G#I81Co#m-"
        "*#XrR_C}=F`Ku9muX>f&GkDog04<YT`ee7A3v>!xTj~cH=xgYl*<OpFJhs!K_iv;&3N{&dDJbP<&MdkTN`Rfun(h"
        ")Kef9g+2SgoN;$y4yv3!s3|2N?$YdJX6OVd%YH0Yx4~;nbfQHBOnz49U^Vk}l1yOUp6&qX`21r+Z5SePS27%19Jj"
        "O~(o2)tbG~0YX~>T(Yx4Rx4!HVmOe6&vO}1@vD+bShyQUQBVkXIag%1<BHoTxkd>*MXvh|aj}9`3E<mvl5$))FrZ"
        "Hs^NFuTcxJ7{I6=7L+rR~JCr~7xTnm#WEMVinenG_uviYh!1KZGT4YO^*Jng)?NS0E^#uNGjuN{={y*@kXH{T?_f"
        "x!O$@T2qbPiH5GAKoETZGj=Q;uGrvfP(7dIf=4nF5=tx{0J06g+sI#vv^6eQ&-"
        "IVF_5p_x0)123Pb)dUdxRuoB+D3u!8!+;!ZgUI5j782YG>-3-LtK;o`J8pJG9%{vu}K-"
        "+KR5MujbG8pbqooU}_$Wa~T|D3AMaK*3zf5lu#X+c*{;>Qm?Mt$jYSzgC6~9j88sFLF8sL>w{1bhcYS86oCO;-"
        "xbMiWmd(*Jb8s;w@?`1XR>GbgBZhS|aDm4v4nU;vnV`v^I6+wd~2AOn@>-"
        "o)YihSt8qWNXP|B2Qe#=q`@#mQZbDO&$}QP`Jfm88KOMtYJI_6dik6+YYYk~&>EKohyrklmML_K^e<V_4_7o#(46"
        "d6&E;`;g?oUaBB1}5U=tB^NezSuTXwq%q55T)qy^`*?Uo}{PY&2oi7LLWZOv#@RbAR&K-"
        "Tis4MC+&Y}gjyu$fd;?=0LH`hjh!943|5f#X24JN3pxtwZEcDbKB6LuTv=kq~u2RCydYE}iH$RO@M?w~xoah^8#Y"
        "j-wlSfcgz;(r}WpjSr1OfJSrJ{-"
        "Ym`54#%bYF&|D|L*;T7)zmmWsC2YZlYvl!XPrKEZme1E|+>1<K^rjWSp|ep&gyfngF1<UF(0(a>Ky^_Bh8`fW*$A"
        "?QFsW6mTk<akr-aTAlS9_3cOuY8#c2^~`~FAgR|k<_kzNy92Vp?ri-G8Fa-ZKg83`x~h{#b_cp>m;Mga-"
        "y!_{xhj@Df*qGacbzO*@U|XHdV}W=lOB#Afe^8PGk0w-)qQXmaBARmL(-"
        "J~pW29*sMlGK?!2K?);mVg?lJp2Zr_^hHgcf3#zq_L3(m6sfdCDwCx-"
        "Suz<aO@f4=iyi@)M;g9EYfLz8|V*!x{E7+Tn9h)o{asbO`ey5iB>Rt3Rg0i$ejRJ6ej-yMlhuvP<C2(t&65AfU2?"
        "&G)nF0`pgyC3InBE7R{=1(??y9Dao8B&LEv2EDEfkQI^CNDkHnEM88Ab!}YHK=X?6n?3SZ}98S;m_e8i}ns$eC1v"
        "C?av{+0>A7ue|m7xyk%qXjkBwZhUBDi+|YAM-%K4w6WZ4I%Pd}IM{_y3CV!HR#wpc-"
        "**F^l8JZKCj>guCl{ETN^FWIfPWa9ce-IPEvPQpnN^bLh+q*6A0i~-"
        "~$xnset<B@NjSXjfmP5kHQ0Fwa96Md6u|Gi})-+Cm(1JktvoK0PmRJ??Ex9nzw*-"
        "=kZkkx%^8#sH>fIyRXA<OY(@^d#5c0`nD#;<?8QVg-HfypMUawG|8v|zqe&@L>yMbrq?Q@iCvW{QDZYzSBWb+c`z"
        "fC0DwYg)^4q^ZfnsE@*Q9&{i!vc;)B>eGDr|0J<$41Nh%GrlH{gh|<P#?9^Rr8hB*9FS#3RZTh=uhn|utbrdiG@t"
        "Gu*WDNrV_9yOAX+xmwjM-SLIZ@VocysBRPKf3tJx?&&^yD2SLs)z0q!0+_;JFh9D8c{yK4#`k8+tN4vTdI}}mk&-"
        "@Tn5_H0W(3^N7l<0}Qk?_Ry;5=OTfGzN4{Cp4o-4*i2MM2pTd7o(;!MjB8_-"
        "Ra^Ua}Q>xlrFVP5@`mc=&|tQnPSz7<WkHj`1@LvQAF+B&-omPhxtFj>45`9Louk2&)Piin9ia$#-"
        "NGyu**MV(4iMSPg(ulWgtk=jE{9AGf_;nG^akd$+y^CvLsBXQE$#0WD_%Y}sTb(z&a7k6b{WasNx<+HYm&Zl5-"
        "BzuZ)Qu)BdI95sM5br&F_HEADDuoQ`8s?$d+>l2^+dxK!-BkU441Y+ImTNPSyHm)590}2~liLb?8Ux8sTSYw-"
        "Q`L7*bFG_g*5>a#rFbrYX_yvff4on>xRQq)}N`7s^hc>K2(@D_<0)`(z|NXt)KK;8-"
        "|4M`KbRI3DS+I&5of&`pFTLKw^PwrtvqgYjF9dM2pTGJGC(Ya>`|GzG`+Fv)=p0X?0O-"
        "q|H9ES<+_6mbE?{|vO#CEVRXTnKePn~(LNffAEyrgA&DaS@;AhHN%n>4^z72aHI&*(EAJM1Dd>LM+qk)E)Bnx9}B"
        "^Gn@;tRh4`^-)9U-KVIl1L|j)M{|VKW&KIXlb0j`{$FRi_`b-"
        "3^W83BcoQ`2Wejhse}XQ@Xd*l3+X)Sr>dCArdXbUaZsHpoIh>=kX2umJ?WsbwrX$G5RHyw)~?X*c%T#pe2O$w9in"
        "*uzPcMjUNQ&gj6^g>qBJeGf`>hd?+|B0ibzNnDvTkUV|+vuAT0q9`kxC?&;adMuc~(P_gW~^W=lD0hia%m$BwvIh"
        "wV6_yaoI^w@-6!a||a7eK=RjWyu0!n>@t>bj1wnPw_xxh?$Ky9xWrqHd;j;6_hn9-"
        "4UwOfkQ!AP8HBE_p5DWI&lLOZ>!CA`&u*F*h+(nX|HMfr(+_9-"
        "Ehz$FGI8$OJ~{;pb}d1da&BblHaj;qnP$hAnyTc{YvgiS82O+o7e;afDWE$Mi>b-7cvP(%M6AfUX$1$;-"
        "^tq?<7&;BOWlBzW^;aC7P|R6u^i=mV!6xTH4Ok*BqCcdSywk_BEg0R)C2&L!h>LLMJh(uD2Ey@j8kY&2XFz^jOT-"
        "#VD%}z;Xae<c~EC=u4YaZP_@I`5P~I(7v~Ix?yMBQ%<CUdv#nH<|KzmMQxf!Aq*ir8;J1|O>|1j7s?!fvJ*vhfrt"
        "n^6{bVdVm{hKXx4u;npHNty7I1QSSv<`7fqHFONn2hiAMjUx_8=$uD3+oVGH7x5@~Sju2Kg83gCsO?lQ=lP(40*b"
        "NIvA1;(UGw)Mkt1rQM?zu!asrw1wqvOjKxlFkiG1OTmJ&@-"
        "|7a_4zp%w^#9D3T|KU}}pWL57+7@XlO<uzTaXA_c+M1r~|Q*I3S7kbIMdy8r~?82Tv16MqJqqn_GD7aLC@JC}tlJ"
        "=zR`;m~SE*eix`x(if|(o3WD05Gm>^;&&rs=eVk(Qjg{c`HG}Uxprr-G-"
        "}NkHL2=3Zl*tnGqP2vjFAIFomACLEwR9ZE=KErb^DsIHveYiQ%_rqQ1f}CxyQOp4UxTYgq`s0UB0-"
        "hp!3K%j5zjy+sV#;SvT1JOMF-th^(m9)3~=9#@RN0H8$LsdPcOG7}6RnZSHmZ5Cgdm;K%=w>Q1|G<be*eT5!ueOR"
        "l_zhw}KfK*7vFl+{p!iac#2B&ju4y?yv!)NgB>bB(|duXe8A2#h&X>4UV2v9Rx&gPDa{Zp2xEk%RJFLD#2*5buBA"
        "nkS*OAaE1-"
        "3wL^9fb|3lH}`<fPvhI<X{bU2ASqe<IUOOci){HqsPGRTU&NRAU3WZu<uO*>4r{3VmED7(}eN2*_O>)aqcEQg)>o"
        "(iW~c&38K&YP2z?VX>TL{BBrtxmEiGEkDt9+=Z7CZl2+E-"
        "sp{6y9EpVVo~tgP!1sW?9HIWnj`+3eoM9LrWEw4#i4-&T*<*4KEDp}3TR-"
        "%oTVzyb8EbMN_Fln3pGDVr6z%n2sAj2EhQ6w3;WzHJyoj!A3^qjTp(Yr2h3k0^p4dL<>EtL#IWz=*hyCYBK@}|0>"
        "hTW%lqMU#&?1MO+Gz~RImpVE7DS&%Sr^0mUfQMjx%%)ep3I#4<_0Xx`|z#O@CJQp=6%p^)EF4w0kfKA^U?FYuE3P"
        "0z>P=yef~+=SayfH<$pkAaRKYd!zE?Heuh%5Zu!;Hda$!Rda|HHwH;=qSvft7x+%WsP1xk2CXO0Df2#LV*nZ#(I#"
        "J7KjexhH9u=Xw#IOj!oka|iF)D-"
        "#v(T3vH+4b+6E6**t;G@L6M>02Dbs?QiCJvl)VOUmoC0oJR=eMh*CPHn61%WG{gGzB<0&I+Xpr&VtKlm;{rI)Z-"
        "r%a;mY8AOCQH|FL;z?S`Vh!#N#-"
        "D;6Zci;<hB6H7u5nDSB%Ak9j2G+%T;Y`G)~}Fg$~WlowbA)p<qfTfE$^!2i6^OEJE_}Jt_VO>Kbsh%%WT(5OWD_k"
        "-;Ka#@gvuU5rLmgW*e^tg3W1?DwArF`oA;ctOTove5fsW=?W;Lx~_{axV9|G{o~#DG=d#C6t=HS@6QY`?1MAchv}"
        "&gM+K~kcu%WU4V?-"
        "YZvq}=*6nz5`Yv~C?gSQ6EPeV7|Kf)Vsx>=j`|CVO~h;r;`}na@slVdZL|ypra4d;S046@2eg|woZYF!UyM7zbL~"
        "T!De7Y0h##&_@{u~Nk-sru(!xDpRR<HbdMZ+RN9C6l*&#4j3Vqg(n#uqryx>H73(DOB7CQB_9gxH@o0HAAMJD1mV"
        "nNYxe5kYCjuScENiClPi2yoMto^61ShZ^b;c^kLaOGiK`S~aIeTK2^rj#sW{)F0H`E_O0V%kZ7iV)L&x?EA<z?Ho"
        "K;mdUI{8V>ImCZvrE1UN>G*{dh-"
        ">NRL0;hbjk6dYenN<TB{A$9_0Xke~Hb}|~^C#HxV!a>~;DiTO(+AZPYhQ$w7cW-"
        "d#B&RzV6h`i{PPFwL*B*a9(?&)cvdT5pv@!-mW$A#2zm2z03(3_8edth@LB_@-"
        "2AS51UhJcvMvwMudRF<7Ql;wq=2bZZS!wI>-"
        "Oo8KS%W3B+tD8T9HW%3T6iDoJz8Q^vEHK`Lh0mSk3}F%+q|6%%1|Tr<Ao#^sEVUZ1E>!Hl{S>c7IApuF3o7_V>Q$"
        "$?#(a5;;w@F157&u3IKJmw<9hK-"
        "_+7)D8ZC8S2xf@enUu5DTTlFPZ#@Vzt!FbxVB|1;}7VC~BvfK4wKc!U%rtx0)|TH<iYTQ!sl}dFpO~x-"
        "%fQ(HcW*sy%1!%8zxvj?Q(=*ya%NEW@-"
        "Y56=*lKu_sv=|kQIhD8akri_)tJOL(}tR4mPAsoe*_|E{uCHnjPswsp}Taq`h8OGNRLH9(}s~D3a_saMLZy5t(rx"
        "b$tBoiIHSQkm7P3}c=QZE{k8=g~vRAj|Dkafw;y@7Ef*K<H*3q6p6;(QuwLQv%*#>8@vabS7BMB~6m&uR<X)imys"
        "T6L(F>r>nrL>n(!*dOQ*!O84f^fWXv5a3n$Mt*D&H%IHh*U%$u14j)Ebtx;DQmUhVBAb?t$0i+^bz11^*grwuQXv"
        "6~v&?}2><*y<8*uDn<^)I00~l%%{g|VVnu^NSC&A9^3L~}|fJW_fuyI>VY+F00(D%r%*tlseO>!geP$~CHqu1eHJ"
        ")@bmZMjkT8xM@mO<GB*nrM6rg5B(a;o*OKwJB7xzbbvLo0yXEe#F4wTB>2WNoh5U7d`sTW;9iFKA8;Q9;*8wg_Wn"
        "=1RcNP&Ee_U$uWlYlV8oK9-"
        "zldH~5oWJ&*^+?ejp14Z#wP+`~LLfkPjv;=u#1z$XrPXbXB6tP6BN?WI1D)eQW3IP9VN&b@92$|D`xq8-"
        "YJr^;das`HPw0raJu<eI(ctcj6uc%y=$`rrXJI@fYlH#9v(00m9vY+$NUt+sFqZZkC1g#N+9D*Dw{Iq=Y5r9OUf*"
        "aaX(A{Ww$rF+d&O$)C>Fl-"
        "t)07YM@)1K9QG=?rgY#sZvWweBonmPf=3=OIB25lNsbllxW%fPF$zM7>RyCy^M;LCh8TSxCb?9$lU4>#E8Z_a_^j"
        "M2E4$X}Omh^Od%o?u2dsB$fEe)+Nj=Y!m5&!rd`sO~J0asxnLzNC1k{ofxzhmQd0jm#qHIpb9;#-"
        "eQ_k+IBtTxTzh{c9<vXjJdz5u41f4-"
        "jJ+X6R@}Bji|y{w#b5zW?9|`+!qzAu|`lVKIlwG&DBjsB%u8%6vH+I^?X`ycszUnadC@ro@#VaFMmaG3VJ8wXtU3"
        "qrzTTVT_s->5;!9T!%#fswpPGg&{VeeX%jBiWahxG>eFpP}IcMaMljuS}yYMmEmd<?**a-"
        "aL$i1JA@t<<6yPPY;+8`pGqvL=AvC(?1(X(#o+`$b7Dr1cnIsZRJ5%qq!VEJ`~L6+8zQdLy77pT>#*Zo%>|JumJ`"
        "f-qoQIQ31qd^Gx0-"
        "5;WezP_#JaK(1dtF>IZr6x<Y*^`>WY)F)<5Un%o>sJ4tk#j!2TJN`z=3ixWBZ@46z7j|ZXxsgE*(^U2#jD5j~|65"
        "5C2BQ&zvijR_n$^Esot$Q+QJgduJ)To_i++e9%nNwpK$~%mC0_?zX#V7pt-"
        "e?0s_={OtdbiA8dC<vP!WJ`fQ1eGOSR2GQ?hI^Qu^ZidR*ga-UD{?1j})0J3{t;qvwdjHYIhuQf)S{BnosJu38rH"
        "OFcOuX^P0!#?(Qq#!5MP~fk4zNF3jMJnY(yci1A9Wc?Fg8810MS6t(AS$1>JoNhJBOdN4DI!3KnSX`~S$*UzIGc3"
        "u+2_~rtdB|y!kTS_4&EcTP(?!d-^mS$c~jd)#_NSXIx-Isvu<`kx9#}))!kS=r_{?gX-ZeLH8ZCDSUiSr!g&`KuR"
        "uY{nW^<Z6$c$t0!>z`&t5?0Es+*(hmgmVL>L0N+rmMuu3^CH`yphh(gWUUXxf?kpA1^h;F`@F=4Ozp}W8lsiOgIc"
        ")CfoRr<+IBZ^rUq_c&Ttw%kq(O8rET2}`rIE;DSoM0babYMki!rVbTeJp<E0;XPNt3z2M&eiDlQqj4ye^Zb`Ts4@"
        "EjcP02H-{eN5e3rm`eM(s=U}Bdwqm`g4L+i&9@ueNOKskD(mBk+|eKv?&2ftpoWlNo&Qx##J?mg-"
        "_L!UqJw%s1fW8xY};NOE00$maJ-Nfax;1@rk%|EYptZMz5F*rr39vGQ$Qm&j9Di&vBXodFiYT(t|-"
        "~IxGqlT2vn4Fy!%JA_IVXJ*%`}=ME)vP+YC!PLe2vCk&q^Ups^;B{Qi=uPoLHuibiBgKvQuXefMQ=&q_8vheQ|^9"
        "ok>mfYjhJs{;K=J43Fdd+cbfH=NmY(8#*cA(WJ>KQ2N*=j_B(H3J;yY^A_K|AYv0F2zgLi)@?Hn6M$zHM#vBUACV"
        "%>n}+F;~@HeG(RfJ9t-"
        "TF%0BY{qdxQ^EA4wav~LD_9UzbgLV+((Je>LOGP2`DfuEmq^HFgXeOdO{Cpk!WL5ecLx)Liq_K>4)}{xJhR&EN?t"
        "ypi+8Ne&l&qgH-%>N^lGT_eqqxG28~Q2w8H@88I6!-kXK-wmJ<;^AH^q=RrY~n`KtmMDj50qwc7p~>Qz0M@;gX}A"
        "@+1bgurf@(r^>)o0Be~5e)8#zWdXVV5GL4BxlW96;qFRpW&w;!>y8fsz<zu$KM63DS7H(EsgNjwV-"
        "e@aYA+f|uIGl25H%dycZW(ASr!_rquVA~X=;N(u{OAP6ZD$PuL!zdT^Ua;DvVvPpko!WPMsb60{b%t)Vpqq2{nCO"
        "xs&u<sk+Ax)Lv2FH5J*a3ZVg|(RmI;9BW0^R28<(44}FXtVw9f_8BbVO(NydkDGMt?=V0gCUW#6AF$U_#+ADAB2N"
        "fM1jG0^JaDH`;8ithF8RfsITU&Z#Oq*hX^~RyWYJ7w)w+gXnTu-"
        "aRTNuz9fsfG0?fSp<PODLp^ZB?Fd?E*5dbY<Ok)Nc0)!?vT%vQ6m!9jW+?cyvp;pSyk~U^@8k!7SgZphbx-nrqHB"
        "A)mhSplAHbvsV$*b9kXUb77V_=XbwargzkQFPDpM!q6d%zZUi>&xcs2?*0-"
        "@EJbF2W}Y6}(X)gg;Rsf>}+5D1&d2#AcU8FIRRJk!EgL;=koTs(!WKn)}OuBPugh@1ThrpAdZaf-A-"
        "_;8XEQHMkcnMG{7)4JN$|8z||gP8{G=OG)(ag^rKGx&0F7YJ8|6<a2ph<72VDKfS?ZFl$rw2UYCRp@KBXHyO@ri$"
        "EA`f3H<bX-_K&qgzeWQEJAhUOpuQcHSlAeyA!$!Szu}+JBUdb4_)UNA;oVi!p%KGk{W!L(3HY4XiC2&K_z=M1_gd"
        "!wR`0XQpY<<rM0mffKiKEF9tm8Xx6knfTf2jejQ}$iyguX32ZNvBB5{o=IqxO~spDe_-"
        "42@18K}r=7zej!!S_g=bZ+a)^Bn=6!Se)5&p>K=}>Tun$*CJYCSq2)j#q-"
        "BexWLRNU?BH_`|D23sHXi~{dBHEn@RaBq$2fzw)r%7q8S00fKN!}Q|2+KPVhoLBY5QS%@hn^KN4P0dmV;AdKPLU+"
        "aB=t(&e%_0>&`^)+ctn!+Gx0&yW-aC+Xdd+L0edJZNNK<x%5`d6t@;A`AU?H{!q&kXYbvy?3)a9fTa=>vP8+a>HS"
        "ua)+(t|6M!)m<$?%6ne6Wcup|-CN-IA<1kWX(J7Oa1~A~}!>;iePN#1cQ!jo|42`Rou2cv41LFh-eeKM(Vthpj(9"
        "KDGj1-"
        "4tFyT|XRQp_*yo6U}ZOh@Qy%SQDu6YM%&(vWKarY@SI*`!C4zR#BS&jC4aO3blOwt|;^UvCLMmgg#TW;?@cekRtN"
        "P6him~NQ#hzGJ2H<PbJ+xCfAeE5Y-"
        "kq)ZNM4!Q5P<QFFR>wjkI|n0fBdTPxE}3M3zEj2T@EXG1E!nJUL$YY*=tb&7F2&SLDYo3z!!#tG@7ScWRclR{#gT"
        "M)lmYDOyV&0()0rFCdX%Yu~3Tc-"
        "<|u$a9m??6<Xz!4M085RYwo|bw4f7biitQWa#VFd;n`VH7<w~c8Iu;l7*%s#6;<R6KDc77Ai_E4U*8>Y81X*cAti"
        "ue$>YGpJ<w{^}kbePTn5|ni8(B(X940_C0h6myT-"
        "^p!yD6XOw1c!^tTP9>>RCX(dq865NgyUg~bdf;YcApmBmr(?r5@l~$#0RUTi}&m&c}pdJQ9_}4a(azUOiz;SJ1Kr"
        "6ZSRwTdMR)og9h!9i5#&59yQl)S{rpTgLOc7^^;L3iN^i?)w*=!EpE%<Ebtr?Glhs+BKH6*RM+-Ie}z)F8GG-Hw!"
        "3xexy}27;ijbK{r=i~=I48zYBqv~_a7K#_3fv8gh_T+MHT3jIkADcCljT(BZ;m({SPbX%{EMfFC2vKZJDP}T5SY|"
        "_x)i)JJXjU8i$TwRWe`=o$2Q{s)Z{3Q(-UJ7*)^$#S}?#gErgQ1|oY>(i(GttlCiD^CUliB;{HA#JG-xQ(`*uP=u"
        "I)%HFHN{d!{2UQgYrtiIWQb$|8SQhld7mz)LQ#j7p!kLT<<((bP5iY%;oM+)fM_47Mo7TpGa=r(x5KBmiH4F{b$z"
        "@R=_Z@Q}dC5Du8wz(pGs_nJm{46`rB-YmUhruFB)muCmqGpp3?5Z3eEnNnkX=Hiac;4<F2(pY)JfLZ*(^XEFDLVb"
        "Q1CXUO78@l3rUSJ4?@cRAEtjqSoHMLCYjVC2E4(7{>kT|I)8%yP-"
        ";InSor^A*UBtCad6n0S(NN8l76J@lY%W)~WW8`&n$dR8oH`g+^z-"
        "2Px*tjUA3Sf7{SB3MieyDur!7s&WLRuPdB7w+v@|X2kdaBM#ZqgOS*gsA25lo2`w49b$xCJZql?x!+8g~aE#6hTF"
        "Fj{(?Bf_5>Z832n^ZKa<qPTGRKlINT*PL+hh5xWo1Ht=@I*cyo+A5L>#mlET!Ox}ah`ly`HmbJcV5(PFv%OO%{s1"
        "3qn>|US|!!G@$y{krjnf8Sjl#bmJU?9TyNCg+Oky8d8Tb-HNmi5Kq|e??cz}dn#gg=-"
        "CpCmLJ5gER3#M<W)I?3wxyi3r<Wkjl4Uk`=tkgnp13E@-"
        "=Ccx{p$hWUQ8ElaO@ykqB*x8kgJ<lZ^>^qwza_6d09XzH_NlZ5--H|v*P;YRHba7&a(_T9ue)%UZkbE;Jr(H=U{%"
        "#mok<?r^r0{Qc}9SIgPM)jI~Gw5R{5y@U>V666@}$>;+nxmZ67bsG~@E8n7zAFK@+v{s$ZmUPM?xmk;85d{?v<$F"
        "M{ePJX#xxM(EaGA;{So&!?`EfD|M@v6Lb*|K$@>rowAkM7Jxr&kFewHG;@fE4|364=xryN$#IFIcEV-MX3Z00ha5"
        "5+`I2juWy^zStQ|_?lQWr{EWDM$}D1(t0N1ff6mTZUvf);BSc+$oMkNQiJUIzgK#ofhpbw{+~ULT|J+iGt8>~hXe"
        "A;Bxn*n8`gV!RrE$Kvu@jH`&}`7;P-MijRE@fYri&Kj>XO4sQ?^KWTXH6+G-"
        "p9@8|vV1XWN6XXy#d(nFNd67Cu!?9mGLs}lqvHM&)PBQ2Rzg)nyNejh}40P%nR$8)-L6E;%bVK8^@_Ni=-"
        "uX~7KgKE8z0Htji-=<z-"
        "iQQPi%XKiiszekZ@`V$uvhD_5QKSK2PywRr!8!)Y!efIApWBtf%x1NF+&Zfqr71y7jmqnJ=nYSF^eG1QNs-"
        "Fv6Lfo@6AXNFgZo-uJ{OXrFs;ezKxeghhg7kDhwqNpqQcWGxS6{?;AH8SeD4GGp-"
        "rLEiB)lVToltTO3G4|r3fASo-ikXC(%OW_DGHUG>mffnd@8xNwnRwP2Pv*tFP*>HqXl9Xh~VCX0GcL$KJYA^Z3K*"
        "n+tJxcKG4#L3utYiyih<IZtH}gV0uj3<drkmv5d(mFrKrpLkxXDq%u-"
        "yBnw1Efq`EBmTAVU96)TVhkWf9pcU2c%;p#OTP4*k2N?racQ_uwe-R9>LF2r9bxUKS`tO5oSeJa+;ki~uN}v-"
        "mE+sAu;?&MPW`D6{j|J&x&1_?XncU!eBmb7_`ROtq)KGa6n413`epYB4QgkT6w#XKRE^G=8lR>dL4@z-"
        "HMh<BwpcYfPZJ7CrlH_G_o%X+NoqfE*pac!roETOMp3YW&M5sQlTAj=a-"
        "ywBSfKR!LElB$2RV~>O@@L)i^Ra`{Cw&Ee0BM6KZjRe<9!f6r(cgo@Xx?#W1RVnirUVYgTzvxss>HeM794WWH_vo"
        "=)O~IIY5K%5s2p?rbml141?wSc2eCx5IW9i{vWzkl(Hpz==yN+9%_#yOHi+wNHmgtt;@B1(7E~LD1vJtH)TrepfD"
        "56bqB8-"
        "D4k@f?jXQ3fdZZ|Iwth;{K!%Y6(3J7Y;mk6`&D@$C~>S8B|UPg`c&Y~4Q6tjxISNx4FWOn1NclAgytpAxjG)*#!>"
        "Rr32|(4P-Czu1{GJNz9hOOv74cXN*WAEpi3n(|4dsZh$Xl5liDy~8|?jlO3tBZ+EheeV-RboycT~~K@g3~bvxBc)"
        "!hN~g`F|`tc>BPRwF)?|DgG&*rj{~Eajg6YV#+DFJjlGp&Nr?w^2MVr#Pc4=m>id`BQU)@vX9GY}^%>#@V2UXAN@"
        "GvtjX(%faa-"
        "+S{{#Rl~ASemyCnTt;qSBbZS1I@evtRKRGNFlM7Sd4rRVuGB&rrJS*AP^53sxkCrWH9dk=ZOk+(2)v;Du~d^{^G$"
        ">54Xd-g>R&~y+BPYwF%{7AsQ_q2-"
        "MPC}2q9}3cq;*kG;Q3nV2XIHu+9avyAe=;Si>!KSIM8h|5xHb1q6wr^L(v>tTiV2K^Bax`etqgCjL}pS^z|E@?2~"
        "|*=pkbhcZXJ5+m2ct>^*5s+bXI3A~H>lEoL5&0%_IY(Ui4Zmlc$9mOi+uoSs7OMJS`83k2031x~|uRw{I2Vi12R?"
        "Z4FF>4)5wCsuv1TY<@P_R1=01B&z0A_B+{5G;1_}znVz@Hb=O_z!M9rDPh<9-"
        "|B?MqOEv$Yl9v}@WzXtbv#yT$0Ff_LdPQ;RZ+huj^B*QVA&{1IqvuunBjLpSW|Z|m+BrgkcgG$Vr<XmcvyLZjJ!J"
        "=L=e)~_otbd|6fTe%Wb=ufPABKM02dfm=~!kY(1jT33?yGz=3JY@6EqavBx*Q{Sb`B71LD<fd-mlMvl(n8-"
        "TLW?ldL+cAE1&b&%T~fdph~X;g1aEo+Dm<*l)l%1}64gtjJOi4bGCN1_-"
        "@Q5g@b;rHVgJ7+4csCvtVpHF53aM}SE-0@L+-0u7}}!(G^}1xs!f|%hRfl&-"
        "boY$ZcOITNGr=$L>2o;;{=<(mKX^i{1osHCTc1B32s|H>9uNcj$aP(MYF(>Ze_p?M`(G1;>73_rLHv28if@`YUn6"
        "n+pqvM+qzkn_+z?53r^hW6g|8qgPENRc`!~D{<rg0t+s&9I#Iw>oQQaBE}6Fr^5sc67?yELc-"
        "6P><#`O~IZN>#2q&64?2BzXDhI=Z(p-~b1~DZ!sf-"
        "(wZME;*cU|$H|H}`jT`_h&_E(g^$*&&bL32k`5kFW;83YlolYsXK@$Oc<k;oBn1XQ1Uz^=M{N%#=&KV&{)0PbL6H"
        "}wtXWUSeA)uP8ugweP6jjr;1UBZ`o_3p<CNo=9Yp{@mtr6w$a%GlHc-kx|E=E*eJ-(VbC4-"
        "BSL1v+;6B(@BQLDAcy5@h*}7)Mb+a7Q{ow}?qkP`?XneWlAWhm9bnxSAm`nsN^lH$=+7!r4Glz-ZBN0_3Y1<JK*L"
        "Y}Ny-R-"
        "%bK?Vl|uuNh0RH4Ourbep?RH3H_vIUFjlk@FhL1=W1t9%2gZ!VQ3OFaWuP*qHLf0H_hlxSZ;md)<*@HL*rT50EoN"
        "1r;FtRnAGF(X)Zi4KVh|Pl-dx5N|j5l7NCIbP{jvAbzxS_(8|;TBmU5aX#M%T)dq+qeSE(W=U+a${~S&4r_c8nc%"
        "Csz44K;81>kTN5xvS#8!NEEQMNr_cOvLaA&$3!W^C`%4M5~iAL$(&-"
        "c=A>8Woq(UxFsbI#}13Ts>G!=2!(ii7cWF)n6R!cQc{M~T-"
        "=e$JVirn&QJLc&W*Y2@GJxhGPn8zR}?K;3H!JO|7d7bXSKY=%|8(Ui>o0u?8)^r5F&0H+n&7gf=^Qs>6^=#C}z!B"
        "#E!N)%O1A)2Min!u7xDy8y%gM{z3>%WQ@772$7(i&2Me><J+Ph&b;)}3V!zmB#S@yOQ)_+tK#Rh*<_ESc^moF6|4"
        "mZ^VJJ5_OQHWi$)6)yorkv0Y>SS7A79pRU)j@f)EuS!TfYhcJ)jRJ?U5ho<pAJ1R=meGo2T9_W3oyFWb>m3{|mri"
        "y?F#w$PGrZy8Qm-HWTLY!910{7sm8LYKdt6l4>kXC~aGGR4aBlEY(3KOfoZAFw2>lsU%nM1J#DsLYD54qLDSZI+O"
        "}!NE4F1{!;t6}yt&#%s4vXl<s{A7F{EW<5bocz9PcOcI|HB2Sq{|7H7sEgkETEK8*bOLa_yi>+3{=4tmfAT6mEK~"
        "FF;(r1l<(Ze%0*Sw4BTl3O)>o2YLkAVwEiTaN+V9v5QsqJrKGDgT`NL;q1`M^CQj9-"
        "XcUk)>ejWq@pk64atGUOX>>2@sO)r;3$fHE@sa}VYR<1temXxnx;Qz8=Rbe?IV2o1FaOQB`h$fMLwQx_^Syh^_)2"
        "9{wUTT4F3ONB%molw(J#A$$*GEb3?-"
        "@(LfUEwjT|m4FpDD3@%$OahmEu=KD))|VI{iYC`yuLoN2Z6Vn4*<u&NJ}|E74cD=b_UQ4U2uNln8+$)_0EH2PE%U"
        "7HV<nffmvqrwkd4SfJS<PVh=gM+Iz>`ZG_2V{o#za^BXMK}2YX#^;kR$eJ5huT)>%WjKECy5^yDDPP%?mGEoDo9+"
        "uV-"
        "p8qT+5qw#b(Df(jir9$|<s$$3<mx(2K?wsUzO7$i$;!k*~?EH)=6JPTUx;`%zbOs$zR|!?gMcVjKK68Vvi^<~SLg"
        "oXvR=7)p=9Vw=sKQzOkh==(r?qIdb*{m;PvKoCo`$MEfbvp4_f`;((Tef;6AczgQs?cv4I_Xfq(=bdhR_g$n|@GX"
        "XZ;09$f-"
        "12=smYOviOT^HqvvdZuXaXhA%2_>5$pa+|kDSI~(+GSz3^DPS?Yb&z!c!5QK0dP>^=i2(g@nX;h9Jj*XoaZSB11O"
        "qYvl$NN-Rvdcv*A}NXAzU5&K#f8luBh10zj#69C&HHt41Md`k;pYA~#nWE%Vkfd3v&S5yTz-"
        "k61HPnkcPL$4%>*FqEa4y^-achroFbWtUJFAO8pAty>P0e0zdCnigG{Yr{}aFth0-"
        "S*9=0A7AR_VI>f?dpu?Ep+N~QOd+tNljlvpC}VQ^$nuc>>^6H$w&IXH<_ni^;q3h`cEmE%qLh)HuB1iKzOW7PP^q"
        "4C{-cxI*e{Z^_h3Ie$|H>pq8nrrB_j}o%P9>S_x70iLGT+A)Zd;N-kDQS2Rhd=#ai*f9gZoU3=--"
        "PqiF5%y?@XhS!g_6#8)AxKA|1^dvk-i7dz&U&~uWgQe@-M9mmOrjysM_nYVb>2|M1CSQIrX-"
        "Sv1LXOvH>9nk;%phH#M)pN%qq-"
        "Ys^H!)kdjEcVF|c3!##^u@?6GjJf`;&O2G4;EY_6HRH&QJNn&5>&JD@e^^&{;@2{nx-TcF<#@jpvHc~Y2vfB50;*"
        "$G`puBX1f+Aj5VP3CNWpl{hTfdP_>06m~Nt5HF`wBoN)#fEAJ;kJ8DF!`MjUVi>N%pjdoR8R@qn0%17@BKv-zYpb"
        "8ZhkX!`PJ?th>a&yf&5eE#qyO~+or_!U({jEDH~WfwYcA@fI6cXlifywdwQT#zlT+@@99t{;1+<dg1V4B9ystT0g"
        "fb~eByy!s-TRY#>J-z^pJ}#wIYZu7(f$xQVv@y0F2kwR(7o{SBOs^-m}-"
        "BJ^Z$0@_ak?NLtJzcN!=EW&4~@mq)+<yKbf`DWQ%wRa750F!d+bSlv00?riz@7xl=Usc+5iy4b`+^3g^-Dz3NA-"
        "zkbeSX@?hWT;&=ej~>JnFSF_dE-RIrlESoK0nkaiaQ<b^|QcfU$TBiItW)ZrR~MS)t8qz)YVnh{6Mh-"
        "+Fjg=TpqAP>~6F}ytWRMWw*?DR(XYJ8620HPKQSqKOCOr`A~F~36IYf3B9NTxk3}X_5^_~RbMe?NY%^^s*Bw0@HG"
        "ah=~jp2N#ZNEh^#1MDmFw@Y>1=S6hZNYu@kyQ?z$^(P^cw1wciz$0%~QL8_}iKR^2?1XyDHs`vv^bprQ5W(XBs^3"
        "#Hgxrs7d?6c5&*Xo;X`iI^y3Bs_Z=qu-"
        "J0Q#T;vX^^3~2ZoBb{s!$eK|+P!VG)zdVf%Ot7)=H;lXdw>kH+xY!Z7d&6{9m7%gP(q@4Qn4?&u{}FdV#Dzoo&x&"
        "h7Tssb-!<*WHAAqTAy0kiW9om1%DO8plJp9!PgoL_~Ql#^IR0^7I|-"
        "Xk>)bJ;T~mym{@q7r1EbuSb293xD|=tsIVOwWyb6Wt98RoBK<gJawZ@eD<47oFUG3PqI?R*{{ZDPJL$O0_XvCQ<n"
        "<~NO@3k1JT!d`jyw2rIUgc*d@PgbT!g;|1tSXt>yuBHH<nNotD9vzS?d|uUQZp?`~y2sDO>xGl~o;b@I6|tM)T8T"
        "!XJAdtz|ahZ(D3wg6WC(&J&IPPNYmj_P1!V1)3KqtG^s&kyFU)=qhfWhgM)lyHo;+F$31>?w&ee<KyZM%)BsLrSn"
        "jca}wLn%7$dFR6TjQeDDIb48G^C*vSm<@eM&zuro;b7JY&zB*8~OHt6`Rj(?zF`n(Q%s^GCQkOt&pU8vK@-mZ-"
        "$A=I|$&<NF`r_cZjtNOIiHAAE=R|AO?&y2~WpwQ*DX+0t<t^$aGWSM099RfSIi=_2i_q)HH7@d47nD?!v$lgw!Js"
        "$ojZ^A3?Hlr_mz`*gNtV(ZJ(Ocw=UNlRwRGhJksK8i7QXS52KK}*WnrzfbDrZ$!G<UxZ$Rr$_xf<SXSMA|bwEj?n"
        "~_7Q+LtZI&sDpi)b?^6n)GgsJT`Vv1uDJXfNMRvvYd2Yb?&N?dZALZF(0d_BvXd0MX9|EfsI}(*y!r}X&$zB7QqI"
        "dfF7Q1R^0~!0f$L~Wu$6q`w+Btxfn}Od%a%lu84E8&0pPvM%fNbgpuUz6?F+I)*EpHA#r?L9Eu+g&rXl?;wE}c#w"
        "=2Cg%}aRESU4gD5Fqff|t5s3S&rM*_gxI>w%g&p*#yJ@a`4)RKcp${eL|9aQfz7w~h#`MgA4M1ytQ1;x)Jb(7y6G"
        "PZJUd{lf05n}GOA_mg)Y9Uj6t`u_Cn*w{QmC{r$@r0{_5nJ^Q)%Y||>$sA-oJmj0hj~C9zA5Je$9vHCN7{SFAZi+"
        "ZDZ7vjuBa96!%E0O7WhR1^!0V@b`9*DfLj#wBOG7t~S5`BTxS=-Fd}~^ATZCQp1<x-"
        "SexcjegHz{A5J}3{=&L=6V!p{;Ax5_vjFflY)v>KA`?$$*bQ`vy+}usc>cS=i1LoDbH>{?Eh_{SQt7-?!Z7>*ft-"
        "T7n4~r#ZX^9J6QAfQI#!A*T|4jjbjbK1+&1x1ZCa?fY=X1gWpZEJ1zIZc&|LH46{^JlUa`M=+#%)y`{XAN`OL|aR"
        "P2|BVCQR-CWgM01GOhV*rgILrG{?p>arXY`@JyT>pI(q~2|XlK^zasMoI-AhV&u=^=8=*$BdHykawxIc@Yhnt2{U"
        "1b`ETmvl_%+%N`e$I?K+t7A;q>TV|oi<wKRJbDw<16o646o;x+d+NHCurt65V+co#4){Ot7TVqK8smjq}&6UW-"
        "&HD2K@FvRXrP@~FkVI)+s^PE8feaEoRx=p{_{H@S)18y_`UtmdBZSIB&E&1T;j9WLCTEON;-"
        ";7b73JMHC9&@U0#`5^$2w?j~b<~X*O)`N~NE4}33I(mU#>XPDp~Md3G1%Py8({N$;L(5naC&k2?z{Eq$Yl#CkpEV"
        "28Eh_OGI2qhqry>nxGrA`XKRc;jtU52Q2irQEE@mq)X<hQABady>u-"
        "$vmBnquFY?ugQ4~8^RLdy}Zq<>C^B1;cf7G~!G2DaN!^_^V-"
        "|rt>Szmf$DXOB^Fe+3XCzg$23Zx{5T8%KSh`Qw>xOIIM>gl>=)R5Q>a7R{R8RIF4{u86t#fAxNSW;Ild?PC=YNru"
        "}+|qS{dAPQAWpWtxqPP~W{TfN>^|5mJKK`CWBthy!yvE8Szz%cgaVpH?-k>Xvd&8YKz5dHC*3o-"
        "ml?u*>_n>fXo$yq1%nU&S_;m@=ud1}qH8ffbYx(d8MJXpLFT;^yu#lyPjGLod@?`pNV4zvzdRjFWRFhF*!wa+gkc"
        "@E^E7@m<xt-gbRHxRVR)tY$d8L8MLO0*W+ibeVRH>iyywV=6P%V$@`(*&9IqJ?-Ux14+m!%1DeU-Wlk6J~|b+_Sl"
        "mXtTa;E^w@p&R&=vmFN>y2~KLtDLJy)`DFZT8S{doI+l97&~g2e4Bw42sPI4!%pe8a`n`PZy=0enAOI+sT>DGx`B"
        "?i!Vp9be`XgIantoCpK80yT0d8|T5AQfKve>g3fyFIAo7VZWZ1k3geOBbg_Kn!?M}5kDW43)E85T92a1-"
        "~*1r~2s2v-"
        "|*@~z~;;*%6!W<i@G=P3*AZTLBhT|fPC>IdXX}aY4y=g0>8XTyyQXGOiUyjTA4RfjjxYzH^<y~(wcN3AD>@d}^f="
        "|#tW`jx_jppb;PmF&nvMBfZ_y5(X#!HknZU5y~hCBGr(BAL8c-"
        "=cy2)%CkcoP6(;Nj_xC&vI`w|BGK8w024@uiNvBEqV7GhEwCAfrIaSFd)?PrsvV4C`P+rWt2wp4)HVAD^5#A5MNe"
        "{doHR-N&`bWn3<{(f$(q0qq^2wGJE}-"
        "nt~So%&kRwJZ4rPL}!Hjdp&4!(|NUdELv?dD!OoFbv*B8PoULrpa<FLvQeM=V<O`-"
        "<@Cd{<#?JoMxJC2f*XQi^Gp67mom8<Be7zJ`-nAbPa+K5D=akJ*-C>@;%gf)ds|E-"
        "}^?W$a~TImJ?{WpqyoISugb5R<xB9Lvx=Waxxjp<m>u7$MW^bhl|ZPT+<1gX!S^%xLTXa93rcKczME5Fx*jB+_mr"
        "{G<^ftrb+^C+1nZ}Bs`sQGe^SxA_IDghHk!=6!_6v9)x__c^U@(45RytY_~sfoEQoyXT$pA1FST+SIlZevrSu(={"
        "p!2PBNwTs@d9f&uHo69u;m8(6sjSDZN&@rh=?cHS3Dn+bX9*6*bT6Z`<pNi9e7kS|{fwT&J8F`<Yd|>sZ#H^G8?q"
        "CS1V_?SX%$Sb9q3!xyMm+29YL#8Q>t9G(Y7g?TCfonN+7R%NZg)qb!>yAIhkh1+W|j&tQv2XI@Z_IN{;cFb+?!=-"
        "H5z4-UFSM?&kFYpdy4>VLSnk-"
        "R%!fTx6)W1`b)y$3CtM|U(P+Fi}j5_QQ0SkUrDH=dQK9+M7iJx98Z%ICi^eSA2=TO@z<HO0}@!J!7;Wg@CaQp3CT"
        "}3bY?F2bpvl~F6U$Z2J8s{^_Q-*}drE{vpP*iAI^9};i*i;vzMeL`>B&7F-8g$7eI;-"
        "4HRO_gA{8YOdw0G6%_!y;+C<h9_Xe12BSs=r64Bmn=wgjG<0Nil|oO?AITAlv`;IE+e2<HF*"
    ),
}

# sha256 of the DECOMPRESSED bytes
EXPECTED = {
    "pipeline.py": "a19d118323c035ce3373f739499677144701a360074b554f33a5e136296a9aaa",
    "train_probe.py": "2eea465e0cc9126787641ddb63cd3c9ff5a9f18e3abd8e63e6e0fa895e275e27",
    "benchmark.py": "8c2bd570c84165f6adcd3b974b5339446fc1a38b943b2548e931f1435a2f0171",
    "tests/smoke_offline.py": "aebedd085ba3b743b0c6f959bee394569dd86e58970045bc866b91611f7a7c6b",
}


def main() -> int:
    force = "--force" in sys.argv[1:]
    unknown = [a for a in sys.argv[1:] if a != "--force"]
    if unknown:
        print("usage: python3 verify.py [--force]")
        print("  --force  overwrite local files that differ from the bundle")
        return 64

    # Phase 1 - verify FIRST, write SECOND (audit finding F-11). The old
    # installer overwrote files in the CWD before checking digests, so a
    # corrupt transfer clobbered local work before reporting itself. Now:
    # decode + hash in memory, compare all digests, continue only if every
    # payload matches.
    print("verifying %d embedded payloads (in memory, nothing written yet)"
          % len(FILES))
    decoded = {}
    bad = []
    for name, payload in FILES.items():
        raw = gzip.decompress(base64.b85decode("".join(payload)))
        digest = hashlib.sha256(raw).hexdigest()
        ok = digest == EXPECTED[name]
        print("  [%s] %-26s %7d bytes  sha256 %s"
              % ("OK " if ok else "BAD", name, len(raw), digest[:16]))
        decoded[name] = raw
        if not ok:
            bad.append(name)

    if bad:
        print("\nCHECKSUM MISMATCH: %s" % ", ".join(bad))
        print("The embedded payload is corrupt - re-copy verify.py in full.")
        print("No files were written.")
        return 2

    # Phase 2 - local-conflict scan BEFORE the first write (reviewer R2).
    # Payload verification alone does not protect local edits: a VALID
    # bundle would otherwise silently overwrite a locally edited file.
    # Any destination that exists and differs is refused by default;
    # identical files are a no-op; --force makes overwriting explicit.
    conflicts, up_to_date, to_write = [], [], []
    for name, raw in decoded.items():
        target = os.path.join(os.getcwd(), name)
        if not os.path.exists(target):
            to_write.append(name)
            continue
        with open(target, "rb") as fh:
            existing = fh.read()
        if hashlib.sha256(existing).hexdigest() == EXPECTED[name]:
            up_to_date.append(name)
        else:
            conflicts.append(name)

    if conflicts and not force:
        print("\nLOCAL CONFLICT: %d destination file(s) differ from the bundle:"
              % len(conflicts))
        for name in conflicts:
            print("  - %s" % name)
        print("Refusing to overwrite local edits. Review them, then keep")
        print("them, or re-run with --force to replace them explicitly.")
        print("No files were written.")
        return 4

    for name in up_to_date:
        print("  [== ] %-26s already up to date (no write)" % name)
    for name in conflicts:
        print("  [!! ] %-26s differs locally - OVERWRITING (--force)" % name)

    print("\nall checksums match - extracting into %s" % os.getcwd())
    post_write_bad = []
    for name in sorted(set(to_write) | set(conflicts)):
        raw = decoded[name]
        target = os.path.join(os.getcwd(), name)
        parent = os.path.dirname(target)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(target, "wb") as fh:
            fh.write(raw)
        # Belt and suspenders: re-hash what actually landed on disk.
        with open(target, "rb") as fh:
            on_disk = hashlib.sha256(fh.read()).hexdigest()
        if on_disk != EXPECTED[name]:
            post_write_bad.append(name)
            print("  [BAD] %s differs on disk after writing" % name)

    if post_write_bad:
        print("\nPOST-WRITE MISMATCH: %s" % ", ".join(post_write_bad))
        return 3

    print("extraction verified from disk")
    if os.path.exists("tests/smoke_offline.py"):
        print("\nrunning offline test suite...\n")
        rc = subprocess.call([sys.executable, "tests/smoke_offline.py"])
        if rc != 0:
            print("\nsmoke suite FAILED (exit %d) - do not start training." % rc)
            return rc
        print("\nsmoke suite PASSED")

    print(r"""
confirm the import (catches a stale copy from an earlier session):
    python3 -c "import pipeline; print(pipeline.__version__)"     # expect 2.0.0

next steps, in a FRESH Kaggle session (no model resident):

  export your HF token first (Add-ons -> Secrets) to avoid Hub rate limits;
  every CLI below falls back to the HF_TOKEN env var automatically:
    import os; from kaggle_secrets import UserSecretsClient
    os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")

  1) train the probe on the TRAIN split (out-of-fold calibration,
     ~25-45 min on 2x T4):
    !python train_probe.py --model "Qwen/Qwen2.5-7B-Instruct" --layer 20 \
        --fpr_limit 0.01 --n_splits 5 --notinject \
        --output probe_qwen_layer20.joblib

  2) evaluate + benchmark with the SAME probe layer(s) you trained.
     A mismatched --layers is refused by the probe fingerprint check
     (that is F-03 working, not a bug):
    !python evaluate_probe.py --probe probe_qwen_layer20.joblib --layer 20
    !python evaluate_end_to_end.py --probe probe_qwen_layer20.joblib \
        --layer 20 --l1_escalate 0.0 --dump_scores e2e_scores.csv
    !python benchmark.py --probe probe_qwen_layer20.joblib --layer 20 \
        --per_dataset 250 --dump_scores bench_scores.csv

  multi-layer variant: train with --layers 12,16,20,24 --output
  probe_qwen_ml.joblib, then pass --layers 12,16,20,24 to EVERY
  eval/benchmark command as well.
""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
